// Copyright (C) 2019-2025 Provable Inc.
// This file is part of the Provable SDK library.

// The Provable SDK library is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// The Provable SDK library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with the Provable SDK library. If not, see <https://www.gnu.org/licenses/>.

mod authorize;
mod deploy;
mod execute;
pub mod imports;
mod join;
mod proving_request;
mod split;
mod transfer;

pub use imports::ProgramImports;
use imports::extract_source;

pub const DEFAULT_URL: &str = "https://api.provable.com/v2";
pub const LOCAL_URL: &str = "http://localhost:3030";

// Dummy verifying key for devnode deployments. Encodes num_public_inputs=64 to accommodate
// functions with many inputs/outputs (e.g. register_token needs 17). Generated by patching
// the original 16-input key's first field (bytes 1-8, u64 LE) to 64.
const DEVNODE_VERIFIER_KEY: &str = "verifier1q9qqqqqqqqqqqqyvxgqqqqqqqqq87vsqqqqqqqqqhe7sqqqqqqqqqma4qqqqqqqqqq65yqqqqqqqqqqvqqqqqqqqqqqgtlaj49fmrk2d8slmselaj9tpucgxv6awu6yu4pfcn5xa0yy0tpxpc8wemasjvvxr9248vt3509vpk3u60ejyfd9xtvjmudpp7ljq2csk4yqz70ug3x8xp3xn3ul0yrrw0mvd2g8ju7rts50u3smue03gp99j88f0ky8h6fjlpvh58rmxv53mldmgrxa3fq6spsh8gt5whvsyu2rk4a2wmeyrgvvdf29pwp02srktxnvht3k6ff094usjtllggva2ym75xc4lzuqu9xx8ylfkm3qc7lf7ktk9uu9du5raukh828dzgq26hrarq5ajjl7pz7zk924kekjrp92r6jh9dpp05mxtuffwlmvew84dvnqrkre7lw29mkdzgdxwe7q8z0vnkv2vwwdraekw2va3plu7rkxhtnkuxvce0qkgxcxn5mtg9q2c3vxdf2r7jjse2g68dgvyh85q4mzfnvn07lletrpty3vypus00gfu9m47rzay4mh5w9f03z9zgzgzhkv0mupdqsk8naljqm9tc2qqzhf6yp3mnv2ey89xk7sw9pslzzlkndfd2upzmew4e4vnrkr556kexs9qrykkuhsr260mnrgh7uv0sp2meky0keeukaxgjdsnmy77kl48g3swcvqdjm50ejzr7x04vy7hn7anhd0xeetclxunnl7pd6e52qxdlr3nmutz4zr8f2xqa57a2zkl59a28w842cj4783zpy9hxw03k6vz4a3uu7sm072uqknpxjk8fyq4vxtqd08kd93c2mt40lj9ag35nm4rwcfjayejk57m9qqu83qnkrj3sz90pw808srmf705n2yu6gvqazpvu2mwm8x6mgtlsntxfhr0qas43rqxnccft36z4ygty86390t7vrt08derz8368z8ekn3yywxgp4uq24gm6e58tpp0lcvtpsm3nkwpnmzztx4qvkaf6vk38wg787h8mfpqqqqqqqqqqffkful";
const DEVNODE_CERTIFICATE: &str =
    "certificate1qyqsqqqqqqqqqqxvwszp09v860w62s2l4g6eqf0kzppyax5we36957ywqm2dplzwvvlqg0kwlnmhzfatnax7uaqt7yqqqw0sc4u";

use crate::{
    KeyPair,
    PrivateKey,
    ProvingKey,
    RecordPlaintext,
    VerifyingKey,
    log,
    types::native::{
        CurrentNetwork,
        IdentifierNative,
        ProcessNative,
        ProgramIDNative,
        ProgramNative,
        ProvingKeyNative,
        VerifyingKeyNative,
    },
};
use snarkvm_console::{network::Network, prelude::ToBytes};
use snarkvm_synthesizer::process::{deployment_cost, minimum_cost_in_microcredits_v2};
use snarkvm_synthesizer_program::StackTrait;
use std::panic::{AssertUnwindSafe, catch_unwind};

use js_sys::{Object, Reflect};
use std::str::FromStr;
use wasm_bindgen::prelude::wasm_bindgen;

#[wasm_bindgen]
#[derive(Clone)]
pub struct ProgramManager;

#[wasm_bindgen]
impl ProgramManager {
    /// Synthesize proving and verifying keys for a program
    ///
    /// @param {string} program The program source code of the program to synthesize keys for
    /// @param {string} function_id The function to synthesize keys for
    /// @param {Array} inputs The inputs to the function
    /// @param {Object | undefined} imports The imports for the program
    /// @param {ProgramImports | undefined} program_imports (optional) A ProgramImports builder with
    /// pre-computed proving and verifying keys for imported programs.
    #[wasm_bindgen(js_name = "synthesizeKeyPair")]
    pub async fn synthesize_keypair(
        private_key: &PrivateKey,
        program: &str,
        function_id: &str,
        inputs: js_sys::Array,
        imports: Option<Object>,
        edition: Option<u16>,
        program_imports: Option<ProgramImports>,
    ) -> Result<KeyPair, String> {
        ProgramManager::execute_function_offline(
            private_key,
            program,
            function_id,
            inputs,
            true,
            true,
            imports,
            None,
            None,
            None,
            None,
            edition,
            program_imports,
        )
        .await?
        .get_keys()
    }

    #[wasm_bindgen(js_name = "loadInclusionProver")]
    pub fn load_inclusion_prover(proving_key: ProvingKey) {
        let result = catch_unwind(AssertUnwindSafe(|| {
            let bytes = ProvingKeyNative::from(proving_key).to_bytes_le().expect("failed to convert to bytes");
            <CurrentNetwork as Network>::inclusion_proving_key(Some(bytes));
        }));

        if let Err(err) = result {
            let msg = if let Some(s) = err.downcast_ref::<&str>() {
                format!("loadInclusionProver panicked: {}", s)
            } else if let Some(s) = err.downcast_ref::<String>() {
                format!("loadInclusionProver panicked: {}", s)
            } else {
                "loadInclusionProver panicked with unknown payload".to_string()
            };
            log(msg.as_str());
        }
    }

    /// Check if a process contains a keypair for a specific function
    pub(crate) fn contains_key(
        process: &ProcessNative,
        program_id: &ProgramIDNative,
        function_id: &IdentifierNative,
    ) -> bool {
        process.get_stack(program_id).map_or_else(
            |_| false,
            |stack| stack.contains_proving_key(function_id) && stack.contains_verifying_key(function_id),
        )
    }

    /// Resolve all imports from the imports object and load them into the process.
    /// Accepts plain string values (`{ "name.aleo": "source" }`) or objects with a
    /// `program` property (`{ "name.aleo": { program: "..." } }`).
    ///
    /// To provide proving/verifying keys for imported programs, use `ProgramImports`
    /// (the builder) instead of this legacy Object path.
    pub(crate) fn resolve_imports(process: &mut ProcessNative, imports: Option<Object>) -> Result<(), String> {
        if let Some(imports) = imports {
            let keys = Object::keys(&imports);
            for i in 0..keys.length() {
                let Some(key) = keys.get(i).as_string() else {
                    continue;
                };
                if key == "credits.aleo" {
                    continue;
                }
                let value = Reflect::get(&imports, &key.as_str().into()).ok();
                if let Some(source) = extract_source(&value) {
                    let import = ProgramNative::from_str(&source).map_err(|e| e.to_string())?;
                    if !process.contains_program(import.id()) {
                        log(&format!("Importing program: {key}"));
                        Self::resolve_program_imports(process, &import, &imports)?;
                        log(&format!("Adding {key} to the process"));
                        process.add_program_with_edition(&import, 1).map_err(|e| e.to_string())?;
                    }
                }
            }
        }
        Ok(())
    }

    /// Recursively resolve a program's static imports in depth-first order.
    fn resolve_program_imports(
        process: &mut ProcessNative,
        program: &ProgramNative,
        imports: &Object,
    ) -> Result<(), String> {
        program.imports().keys().try_for_each(|program_id| {
            let program_id = program_id.to_string();
            if program_id == "credits.aleo" {
                return Ok(());
            }
            let value = Reflect::get(imports, &program_id.as_str().into()).ok();
            if let Some(source) = extract_source(&value) {
                let import = ProgramNative::from_str(&source).map_err(|err| err.to_string())?;
                if !process.contains_program(import.id()) {
                    log(&format!("Importing program: {program_id}"));
                    Self::resolve_program_imports(process, &import, imports)?;
                    log(&format!("Adding {program_id} to the process"));
                    process.add_program_with_edition(&import, 1).map_err(|err| err.to_string())?;
                }
            }
            Ok::<(), String>(())
        })
    }

    /// Resolve imports using either the zero-cost `ProgramImports` builder or the
    /// legacy `Object` format. If `program_imports` is provided, it takes precedence
    /// over `imports`.
    pub(crate) fn resolve_imports_or_builder(
        process: &mut ProcessNative,
        imports: Option<Object>,
        program_imports: Option<&ProgramImports>,
    ) -> Result<(), String> {
        if let Some(pi) = program_imports { pi.load_programs(process) } else { Self::resolve_imports(process, imports) }
    }

    pub(crate) fn validate_fee_record(
        fee_record: &Option<RecordPlaintext>,
        minimum_execution_cost: u64,
        priority_fee_microcredits: u64,
    ) -> Result<(), String> {
        let total_fee = priority_fee_microcredits.saturating_add(minimum_execution_cost);
        if let Some(fee_record) = fee_record {
            log("Validating the fee record");
            if fee_record.microcredits() < total_fee {
                return Err(format!(
                    "Fee record does not have enough credits to pay for a fee of {} credits. (base fee: {} credits - priority fee: {} credits)",
                    total_fee as f64 / 1_000_000.0,
                    minimum_execution_cost as f64 / 1_000_000.0,
                    priority_fee_microcredits as f64 / 1_000_000.0,
                ));
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::Metadata;
    use js_sys::{Object, Reflect};
    use wasm_bindgen::{JsCast, JsValue};
    use wasm_bindgen_test::*;

    pub const MULTIPLY_PROGRAM: &str = r#"// The 'multiply_test.aleo' program which is imported by the 'double_test.aleo' program.
program multiply_test.aleo;

function multiply:
    input r0 as u32.public;
    input r1 as u32.private;
    mul r0 r1 into r2;
    output r2 as u32.private;
"#;

    pub const MULTIPLY_IMPORT_PROGRAM: &str = r#"// The 'double_test.aleo' program that uses a single import from another program to perform doubling.
import multiply_test.aleo;

program double_test.aleo;

function double_it:
    input r0 as u32.private;
    call multiply_test.aleo/multiply 2u32 r0 into r1;
    output r1 as u32.private;
"#;

    pub const ADDITION_PROGRAM: &str = r#"// The 'addition_test.aleo' program is imported by the 'double_test.aleo' program.
program addition_test.aleo;

function binary_add:
    input r0 as u32.public;
    input r1 as u32.private;
    add r0 r1 into r2;
    output r2 as u32.private;
"#;

    pub const NESTED_IMPORT_PROGRAM: &str = r#"// The 'imported_add_mul.aleo' program uses a nested series of imports. It imports the 'double_test.aleo' program
// which then imports the 'multiply_test.aleo' program and implicitly uses that to perform the doubling.
import double_test.aleo;
import addition_test.aleo;

program imported_add_mul.aleo;

function add_and_double:
    input r0 as u32.public;
    input r1 as u32.private;
    call addition_test.aleo/binary_add r0 r1 into r2;
    call double_test.aleo/double_it r2 into r3;
    output r3 as u32.private;
"#;

    #[wasm_bindgen_test]
    fn test_import_resolution() {
        let imports = Object::new();
        Reflect::set(&imports, &JsValue::from_str("multiply_test.aleo"), &JsValue::from_str(MULTIPLY_PROGRAM)).unwrap();
        Reflect::set(&imports, &JsValue::from_str("addition_test.aleo"), &JsValue::from_str(ADDITION_PROGRAM)).unwrap();
        Reflect::set(&imports, &JsValue::from_str("double_test.aleo"), &JsValue::from_str(MULTIPLY_IMPORT_PROGRAM))
            .unwrap();

        let mut process = ProcessNative::load_web().unwrap();
        let add_program = ProgramNative::from_str(ADDITION_PROGRAM).unwrap();
        let multiply_program = ProgramNative::from_str(MULTIPLY_PROGRAM).unwrap();
        let double_program = ProgramNative::from_str(MULTIPLY_IMPORT_PROGRAM).unwrap();

        ProgramManager::resolve_imports(&mut process, Some(imports)).unwrap();

        assert!(process.contains_program(add_program.id()));
        assert!(process.contains_program(multiply_program.id()));
        assert!(process.contains_program(double_program.id()));
    }

    #[wasm_bindgen_test]
    async fn test_load_inclusion_prover() {
        let inclusion_prover_url = Metadata::inclusion().prover;
        console_log!("inclusion prover url: {}", inclusion_prover_url);

        let bytes = reqwest::get(inclusion_prover_url).await.unwrap().bytes().await.unwrap().to_vec();
        let key = ProvingKey::from_bytes(&bytes).unwrap();
        ProgramManager::load_inclusion_prover(key);
    }

    /// A simple program that returns a constant value. Used as a dynamic dispatch target.
    pub const DD_CONSTANTS_PROGRAM: &str = r#"program dd_constants.aleo;

function get_value:
    output 42u128 as u128.private;

constructor:
    assert.eq true true;
"#;

    /// A program that calls another program via `call.dynamic`. The first three inputs
    /// are field-encoded identifiers for (program_name, network, function_name).
    /// It calls the target, adds 1 to the result, and returns it.
    pub const DD_CALLER_PROGRAM: &str = r#"program dd_caller.aleo;

function call_and_increment:
    input r0 as field.public;
    input r1 as field.public;
    input r2 as field.public;
    call.dynamic r0 r1 r2 into r3 (as u128.private);
    add r3 1u128 into r4;
    output r4 as u128.public;

constructor:
    assert.eq true true;
"#;

    /// A second simple program that returns a constant value. Used as a second dynamic dispatch target.
    pub const DD_TEN_PROGRAM: &str = r#"program dd_ten.aleo;

function get_ten:
    output 10u128 as u128.private;

constructor:
    assert.eq true true;
"#;

    /// A program that calls TWO different programs via `call.dynamic` and adds the results.
    /// Calls dd_constants/get_value → 42u128, then dd_ten/get_ten → 10u128, returns 52u128.
    pub const DD_MULTI_CALLER_PROGRAM: &str = r#"program dd_multi_caller.aleo;

function call_two_and_add:
    input r0 as field.public;
    input r1 as field.public;
    input r2 as field.public;
    input r3 as field.public;
    input r4 as field.public;
    call.dynamic r0 r1 r2 into r5 (as u128.private);
    call.dynamic r3 r1 r4 into r6 (as u128.private);
    add r5 r6 into r7;
    output r7 as u128.public;

constructor:
    assert.eq true true;
"#;

    /// Test that resolve_imports loads programs from the imports object that are
    /// not statically imported by the caller (i.e. dynamic dispatch targets).
    #[wasm_bindgen_test]
    fn test_resolve_dynamic_imports() {
        let dd_constants = ProgramNative::from_str(DD_CONSTANTS_PROGRAM).unwrap();

        // Build imports object containing the dynamic target.
        let imports = Object::new();
        Reflect::set(&imports, &JsValue::from_str("dd_constants.aleo"), &JsValue::from_str(DD_CONSTANTS_PROGRAM))
            .unwrap();

        // resolve_imports should load dd_constants even though it's not a static import of dd_caller.
        let mut process = ProcessNative::load_web().unwrap();
        ProgramManager::resolve_imports(&mut process, Some(imports)).unwrap();
        assert!(
            process.contains_program(dd_constants.id()),
            "resolve_imports should load all programs from the imports object"
        );
    }

    /// Test that resolve_imports correctly loads multiple dynamic targets
    /// from a single imports object.
    #[wasm_bindgen_test]
    fn test_resolve_multiple_dynamic_imports() {
        let dd_constants = ProgramNative::from_str(DD_CONSTANTS_PROGRAM).unwrap();
        let dd_ten = ProgramNative::from_str(DD_TEN_PROGRAM).unwrap();

        // Build imports object containing both dynamic targets.
        let imports = Object::new();
        Reflect::set(&imports, &JsValue::from_str("dd_constants.aleo"), &JsValue::from_str(DD_CONSTANTS_PROGRAM))
            .unwrap();
        Reflect::set(&imports, &JsValue::from_str("dd_ten.aleo"), &JsValue::from_str(DD_TEN_PROGRAM)).unwrap();

        let mut process = ProcessNative::load_web().unwrap();

        // resolve_imports should load both dynamic targets.
        ProgramManager::resolve_imports(&mut process, Some(imports)).unwrap();
        assert!(process.contains_program(dd_constants.id()), "resolve_imports should load dd_constants.aleo");
        assert!(process.contains_program(dd_ten.id()), "resolve_imports should load dd_ten.aleo");
    }

    /// Test that resolve_imports correctly handles structured import entries
    /// (objects with a `source` property) alongside plain string entries.
    #[wasm_bindgen_test]
    fn test_resolve_structured_imports() {
        let multiply_program = ProgramNative::from_str(MULTIPLY_PROGRAM).unwrap();
        let addition_program = ProgramNative::from_str(ADDITION_PROGRAM).unwrap();

        let imports = Object::new();

        // Structured entry: object with `source` field.
        let structured_entry = Object::new();
        Reflect::set(&structured_entry, &JsValue::from_str("program"), &JsValue::from_str(MULTIPLY_PROGRAM)).unwrap();
        Reflect::set(&imports, &JsValue::from_str("multiply_test.aleo"), &structured_entry.into()).unwrap();

        // Plain string entry (backward compat).
        Reflect::set(&imports, &JsValue::from_str("addition_test.aleo"), &JsValue::from_str(ADDITION_PROGRAM)).unwrap();

        let mut process = ProcessNative::load_web().unwrap();
        ProgramManager::resolve_imports(&mut process, Some(imports)).unwrap();

        assert!(process.contains_program(multiply_program.id()), "Structured import entry should load the program");
        assert!(process.contains_program(addition_program.id()), "Plain string import entry should still work");
    }

    /// Test that resolve_imports handles mixed structured and transitive imports.
    #[wasm_bindgen_test]
    fn test_resolve_structured_imports_with_transitive_deps() {
        let multiply_program = ProgramNative::from_str(MULTIPLY_PROGRAM).unwrap();
        let double_program = ProgramNative::from_str(MULTIPLY_IMPORT_PROGRAM).unwrap();

        let imports = Object::new();

        // multiply_test.aleo as plain string (will be resolved as transitive dep).
        Reflect::set(&imports, &JsValue::from_str("multiply_test.aleo"), &JsValue::from_str(MULTIPLY_PROGRAM)).unwrap();

        // double_test.aleo as structured entry (imports multiply_test.aleo statically).
        let structured_entry = Object::new();
        Reflect::set(&structured_entry, &JsValue::from_str("program"), &JsValue::from_str(MULTIPLY_IMPORT_PROGRAM))
            .unwrap();
        Reflect::set(&imports, &JsValue::from_str("double_test.aleo"), &structured_entry.into()).unwrap();

        let mut process = ProcessNative::load_web().unwrap();
        ProgramManager::resolve_imports(&mut process, Some(imports)).unwrap();

        assert!(process.contains_program(multiply_program.id()), "Transitive dependency should be loaded");
        assert!(process.contains_program(double_program.id()), "Structured import should be loaded");
    }

    // ───────────────────────────────────────────────────────────────────
    // ProgramImports builder tests
    // ───────────────────────────────────────────────────────────────────

    /// Test basic ProgramImports builder operations: new, add_program, is_empty, contains.
    #[wasm_bindgen_test]
    fn test_program_imports_builder_basic() {
        let mut builder = ProgramImports::new();
        assert!(builder.is_empty(), "New builder should be empty");
        assert!(!builder.contains("multiply_test.aleo"));

        builder.add_program("multiply_test.aleo", MULTIPLY_PROGRAM, None).unwrap();
        assert!(!builder.is_empty(), "Builder should not be empty after add");
        assert!(builder.contains("multiply_test.aleo"));
        assert!(!builder.contains("addition_test.aleo"));

        builder.add_program("addition_test.aleo", ADDITION_PROGRAM, None).unwrap();
        assert!(builder.contains("addition_test.aleo"));
    }

    /// Test that load_programs loads programs into the process via the builder path.
    #[wasm_bindgen_test]
    fn test_program_imports_load_programs() {
        let mut builder = ProgramImports::new();
        builder.add_program("multiply_test.aleo", MULTIPLY_PROGRAM, None).unwrap();
        builder.add_program("addition_test.aleo", ADDITION_PROGRAM, None).unwrap();

        let multiply_program = ProgramNative::from_str(MULTIPLY_PROGRAM).unwrap();
        let addition_program = ProgramNative::from_str(ADDITION_PROGRAM).unwrap();

        let mut process = ProcessNative::load_web().unwrap();
        builder.load_programs(&mut process).unwrap();

        assert!(process.contains_program(multiply_program.id()), "multiply_test.aleo should be in process");
        assert!(process.contains_program(addition_program.id()), "addition_test.aleo should be in process");
    }

    /// Test that load_programs handles transitive dependencies via the builder's own recursive resolution.
    #[wasm_bindgen_test]
    fn test_program_imports_load_programs_transitive() {
        let mut builder = ProgramImports::new();
        builder.add_program("multiply_test.aleo", MULTIPLY_PROGRAM, None).unwrap();
        builder.add_program("double_test.aleo", MULTIPLY_IMPORT_PROGRAM, None).unwrap();

        let multiply_program = ProgramNative::from_str(MULTIPLY_PROGRAM).unwrap();
        let double_program = ProgramNative::from_str(MULTIPLY_IMPORT_PROGRAM).unwrap();

        let mut process = ProcessNative::load_web().unwrap();
        builder.load_programs(&mut process).unwrap();

        assert!(process.contains_program(multiply_program.id()), "Transitive dep should be loaded");
        assert!(process.contains_program(double_program.id()), "Direct import should be loaded");
    }

    /// Test that resolve_imports_or_builder prefers the builder when both are provided.
    #[wasm_bindgen_test]
    fn test_resolve_imports_or_builder_prefers_builder() {
        // Legacy Object has only multiply_test.aleo.
        let legacy = Object::new();
        Reflect::set(&legacy, &JsValue::from_str("multiply_test.aleo"), &JsValue::from_str(MULTIPLY_PROGRAM)).unwrap();

        // Builder has only addition_test.aleo.
        let mut builder = ProgramImports::new();
        builder.add_program("addition_test.aleo", ADDITION_PROGRAM, None).unwrap();

        let multiply_program = ProgramNative::from_str(MULTIPLY_PROGRAM).unwrap();
        let addition_program = ProgramNative::from_str(ADDITION_PROGRAM).unwrap();

        let mut process = ProcessNative::load_web().unwrap();
        ProgramManager::resolve_imports_or_builder(&mut process, Some(legacy), Some(&builder)).unwrap();

        // Builder should win — addition_test loaded, multiply_test NOT loaded.
        assert!(
            process.contains_program(addition_program.id()),
            "Builder's program should be loaded when both are provided"
        );
        assert!(
            !process.contains_program(multiply_program.id()),
            "Legacy Object's program should NOT be loaded when builder is provided"
        );
    }

    /// Test ProgramImports::from_object creates a builder from a plain JS object.
    #[wasm_bindgen_test]
    fn test_program_imports_from_object() {
        let obj = Object::new();
        Reflect::set(&obj, &JsValue::from_str("multiply_test.aleo"), &JsValue::from_str(MULTIPLY_PROGRAM)).unwrap();
        Reflect::set(&obj, &JsValue::from_str("addition_test.aleo"), &JsValue::from_str(ADDITION_PROGRAM)).unwrap();

        let builder = ProgramImports::from_object(obj);
        assert!(!builder.is_empty());
        assert!(builder.contains("multiply_test.aleo"));
        assert!(builder.contains("addition_test.aleo"));
        assert!(!builder.contains("nonexistent.aleo"));
    }

    /// Test ProgramImports::from_object with structured entries (objects with `source` field).
    #[wasm_bindgen_test]
    fn test_program_imports_from_object_structured() {
        let obj = Object::new();

        // Structured entry.
        let structured = Object::new();
        Reflect::set(&structured, &JsValue::from_str("program"), &JsValue::from_str(MULTIPLY_PROGRAM)).unwrap();
        Reflect::set(&obj, &JsValue::from_str("multiply_test.aleo"), &structured.into()).unwrap();

        // Plain string entry.
        Reflect::set(&obj, &JsValue::from_str("addition_test.aleo"), &JsValue::from_str(ADDITION_PROGRAM)).unwrap();

        let builder = ProgramImports::from_object(obj);
        assert!(builder.contains("multiply_test.aleo"), "Structured entry should be parsed");
        assert!(builder.contains("addition_test.aleo"), "Plain string entry should be parsed");
    }

    /// Test ProgramImports::from_object with structured entries that include a `keys` property.
    /// Verifies that the `keys` object is parsed without errors and non-Uint8Array values
    /// are silently skipped.
    #[wasm_bindgen_test]
    fn test_program_imports_from_object_structured_with_keys() {
        let obj = Object::new();

        // Build a structured entry with a `keys` map containing non-Uint8Array placeholder values.
        let structured = Object::new();
        Reflect::set(&structured, &JsValue::from_str("program"), &JsValue::from_str(MULTIPLY_PROGRAM)).unwrap();

        let keys_map = Object::new();
        let fn_keys = Object::new();
        // These are strings, not Uint8Array, so dyn_into will fail and they should be silently skipped.
        Reflect::set(&fn_keys, &JsValue::from_str("provingKey"), &JsValue::from_str("not a key")).unwrap();
        Reflect::set(&fn_keys, &JsValue::from_str("verifyingKey"), &JsValue::from_str("not a key")).unwrap();
        Reflect::set(&keys_map, &JsValue::from_str("multiply"), &fn_keys.into()).unwrap();
        Reflect::set(&structured, &JsValue::from_str("keys"), &keys_map.into()).unwrap();

        Reflect::set(&obj, &JsValue::from_str("multiply_test.aleo"), &structured.into()).unwrap();

        let builder = ProgramImports::from_object(obj);
        // Program should still be added even though key extraction was skipped.
        assert!(builder.contains("multiply_test.aleo"), "Program should be added despite invalid key types");
    }

    /// Test ProgramImports::to_object round-trips program sources.
    #[wasm_bindgen_test]
    fn test_program_imports_to_object() {
        let mut builder = ProgramImports::new();
        builder.add_program("multiply_test.aleo", MULTIPLY_PROGRAM, None).unwrap();
        builder.add_program("addition_test.aleo", ADDITION_PROGRAM, None).unwrap();

        let obj = builder.to_object();

        // Verify keys exist.
        let mul_val = Reflect::get(&obj, &JsValue::from_str("multiply_test.aleo")).unwrap();
        let add_val = Reflect::get(&obj, &JsValue::from_str("addition_test.aleo")).unwrap();
        assert!(mul_val.is_string(), "multiply_test.aleo should be a string in the output");
        assert!(add_val.is_string(), "addition_test.aleo should be a string in the output");

        // Verify the source strings are valid programs (round-trip parse).
        let mul_src = mul_val.as_string().unwrap();
        let add_src = add_val.as_string().unwrap();
        assert!(ProgramNative::from_str(&mul_src).is_ok(), "multiply_test source should be valid");
        assert!(ProgramNative::from_str(&add_src).is_ok(), "addition_test source should be valid");
    }

    /// Test getProvingKey / getVerifyingKey return None when no keys have been added.
    #[wasm_bindgen_test]
    fn test_program_imports_get_keys_returns_none_without_keys() {
        let mut builder = ProgramImports::new();
        builder.add_program("multiply_test.aleo", MULTIPLY_PROGRAM, None).unwrap();

        // No keys added — get should return None.
        assert!(builder.get_proving_key("multiply_test.aleo", "multiply").is_none());
        assert!(builder.get_verifying_key("multiply_test.aleo", "multiply").is_none());

        // Unknown program — should also return None.
        assert!(builder.get_proving_key("nonexistent.aleo", "foo").is_none());
        assert!(builder.get_verifying_key("nonexistent.aleo", "foo").is_none());
    }

    /// Test extract_keys is a safe no-op when no keys exist in the process.
    #[wasm_bindgen_test]
    fn test_program_imports_extract_keys_noop() {
        let mut builder = ProgramImports::new();
        builder.add_program("multiply_test.aleo", MULTIPLY_PROGRAM, None).unwrap();

        // Load programs into the process (no execution, so no keys synthesized).
        let mut process = ProcessNative::load_web().unwrap();
        builder.load_programs(&mut process).unwrap();

        // extract_keys should be a safe no-op — no keys to extract.
        builder.extract_keys(&process);

        // Verify no keys were extracted (none existed).
        assert!(builder.get_proving_key("multiply_test.aleo", "multiply").is_none());
        assert!(builder.get_verifying_key("multiply_test.aleo", "multiply").is_none());
    }

    /// Test add_program with explicit edition parameter.
    #[wasm_bindgen_test]
    fn test_program_imports_add_program_with_edition() {
        let mut builder = ProgramImports::new();
        // Edition 2 — should still load successfully.
        builder.add_program("multiply_test.aleo", MULTIPLY_PROGRAM, Some(2)).unwrap();
        assert!(builder.contains("multiply_test.aleo"));

        let mut process = ProcessNative::load_web().unwrap();
        builder.load_programs(&mut process).unwrap();
        let multiply_program = ProgramNative::from_str(MULTIPLY_PROGRAM).unwrap();
        assert!(process.contains_program(multiply_program.id()));
    }

    /// Test add_program rejects invalid source code.
    #[wasm_bindgen_test]
    fn test_program_imports_add_program_invalid_source() {
        let mut builder = ProgramImports::new();
        let result = builder.add_program("bad.aleo", "this is not valid aleo code", None);
        assert!(result.is_err(), "Invalid source code should return an error");
    }

    /// Test that addProvingKeyBytes / addVerifyingKeyBytes require an existing program.
    #[wasm_bindgen_test]
    fn test_program_imports_add_key_bytes_requires_program() {
        let mut builder = ProgramImports::new();
        let result = builder.add_proving_key_bytes("nonexistent.aleo", "multiply", &[0u8; 4]);
        assert!(result.is_err(), "Should fail when program not added");
        assert!(result.unwrap_err().contains("must be added via addProgram"));

        let result = builder.add_verifying_key_bytes("nonexistent.aleo", "multiply", &[0u8; 4]);
        assert!(result.is_err(), "Should fail when program not added");
        assert!(result.unwrap_err().contains("must be added via addProgram"));
    }

    /// Test that addProvingKeyBytes / addVerifyingKeyBytes reject invalid bytes.
    #[wasm_bindgen_test]
    fn test_program_imports_add_key_bytes_invalid() {
        let mut builder = ProgramImports::new();
        builder.add_program("multiply_test.aleo", MULTIPLY_PROGRAM, None).unwrap();

        let result = builder.add_proving_key_bytes("multiply_test.aleo", "multiply", &[0u8; 4]);
        assert!(result.is_err(), "Invalid bytes should fail deserialization");

        let result = builder.add_verifying_key_bytes("multiply_test.aleo", "multiply", &[0u8; 4]);
        assert!(result.is_err(), "Invalid bytes should fail deserialization");
    }

    /// Test that addProvingKeyBytes / addVerifyingKeyBytes successfully round-trip
    /// with real key bytes from the built-in verifier parameters.
    #[wasm_bindgen_test]
    fn test_program_imports_add_verifying_key_bytes_roundtrip() {
        // Load real verifying key bytes from built-in parameters.
        let vk_bytes = crate::types::native::parameters::TransferPublicVerifier::load_bytes().unwrap();
        let vk = VerifyingKey::from_bytes(&vk_bytes).unwrap();

        let mut builder = ProgramImports::new();
        builder.add_program("multiply_test.aleo", MULTIPLY_PROGRAM, None).unwrap();
        builder.add_verifying_key_bytes("multiply_test.aleo", "multiply", &vk_bytes).unwrap();

        // Extract via getter and verify it matches.
        let extracted = builder.get_verifying_key("multiply_test.aleo", "multiply").unwrap();
        assert_eq!(extracted.checksum(), vk.checksum(), "Round-tripped verifying key should match");
    }

    /// Test that to_object outputs structured format with keys as Uint8Array when keys are present.
    #[wasm_bindgen_test]
    fn test_program_imports_to_object_with_keys() {
        let vk_bytes = crate::types::native::parameters::TransferPublicVerifier::load_bytes().unwrap();

        let mut builder = ProgramImports::new();
        builder.add_program("multiply_test.aleo", MULTIPLY_PROGRAM, None).unwrap();
        builder.add_verifying_key_bytes("multiply_test.aleo", "multiply", &vk_bytes).unwrap();

        // Also add a program without keys to verify it uses the simple format.
        builder.add_program("addition_test.aleo", ADDITION_PROGRAM, None).unwrap();

        let obj = builder.to_object();

        // addition_test.aleo should be a plain string (no keys).
        let add_val = Reflect::get(&obj, &JsValue::from_str("addition_test.aleo")).unwrap();
        assert!(add_val.is_string(), "Program without keys should use plain string format");

        // multiply_test.aleo should be a structured object.
        let mul_val = Reflect::get(&obj, &JsValue::from_str("multiply_test.aleo")).unwrap();
        assert!(!mul_val.is_string(), "Program with keys should use structured format");

        // Verify source is present.
        let source = Reflect::get(&mul_val, &JsValue::from_str("program")).unwrap();
        assert!(source.is_string(), "Structured entry should have a source property");
        assert!(ProgramNative::from_str(&source.as_string().unwrap()).is_ok(), "Source should be valid program");

        // Verify keys structure.
        let keys = Reflect::get(&mul_val, &JsValue::from_str("keys")).unwrap();
        assert!(!keys.is_undefined(), "Structured entry should have a keys property");

        let fn_keys = Reflect::get(&keys, &JsValue::from_str("multiply")).unwrap();
        assert!(!fn_keys.is_undefined(), "Keys should contain the function name");

        let vk_val = Reflect::get(&fn_keys, &JsValue::from_str("verifyingKey")).unwrap();
        assert!(vk_val.is_instance_of::<js_sys::Uint8Array>(), "Verifying key should be a Uint8Array");
    }

    /// Test that to_object → fromObject round-trips keys via Uint8Array bytes.
    #[wasm_bindgen_test]
    fn test_program_imports_to_object_from_object_roundtrip_keys() {
        let vk_bytes = crate::types::native::parameters::TransferPublicVerifier::load_bytes().unwrap();
        let original_checksum = VerifyingKey::from_bytes(&vk_bytes).unwrap().checksum();

        let mut builder = ProgramImports::new();
        builder.add_program("multiply_test.aleo", MULTIPLY_PROGRAM, None).unwrap();
        builder.add_verifying_key_bytes("multiply_test.aleo", "multiply", &vk_bytes).unwrap();

        // Round-trip: to_object → fromObject.
        let obj = builder.to_object();
        let mut restored = ProgramImports::from_object(obj);

        assert!(restored.contains("multiply_test.aleo"), "Program should survive round-trip");

        // Verify the verifying key survived the round-trip.
        let restored_vk = restored.get_verifying_key("multiply_test.aleo", "multiply");
        assert!(restored_vk.is_some(), "Verifying key should survive to_object → fromObject round-trip");
        assert_eq!(
            restored_vk.unwrap().checksum(),
            original_checksum,
            "Round-tripped verifying key should have same checksum"
        );
    }
}
