name: Setup Rust
description: Sets up Rust
runs:
  using: "composite"
  steps:
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Initialize Rustup
      shell: bash
      run: |
        rustup show
