// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#include "HybridScalarTestnet.hpp"

#include <stdexcept>

namespace margelo::nitro::shield {

HybridScalarTestnet::HybridScalarTestnet() : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()), handle_(std::nullopt) {}

HybridScalarTestnet::HybridScalarTestnet(rust::Box<shield_testnet::ScalarHandle>&& handle)
    : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()), handle_(std::move(handle)) {}

HybridScalarTestnet::~HybridScalarTestnet() {
  release();
}

std::shared_ptr<HybridScalarSpec> HybridScalarTestnet::create() {
  return std::make_shared<HybridScalarTestnet>();
}

std::shared_ptr<HybridScalarSpec> HybridScalarTestnet::fromString(const std::string& value) {
  return std::make_shared<HybridScalarTestnet>(createHandle(value));
}

std::shared_ptr<HybridScalarSpec> HybridScalarTestnet::clone() {
  auto cloned = cloneHandle(ensureHandle());
  return std::make_shared<HybridScalarTestnet>(std::move(cloned));
}

std::string HybridScalarTestnet::toString() {
  auto result = ensureHandle().scalar_to_string();
  return std::string(result);
}

shield_testnet::ScalarHandle& HybridScalarTestnet::ensureHandle() const {
  if (!handle_.has_value()) {
    throw std::runtime_error("Scalar handle is not initialized");
  }
  return **handle_;
}

rust::Box<shield_testnet::ScalarHandle> HybridScalarTestnet::createHandle(const std::string& value) {
  auto handle = shield_testnet::scalar_from_string(rust::String(value));
  return handle;
}

rust::Box<shield_testnet::ScalarHandle> HybridScalarTestnet::cloneHandle(shield_testnet::ScalarHandle& handle) {
  auto result = handle.scalar_clone();
  return result;
}

void HybridScalarTestnet::release() {
  if (handle_.has_value()) {
    handle_.reset();
  }
}

} // namespace margelo::nitro::shield
