// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#pragma once

#include "HybridFieldSpec.hpp"
#include <NitroModules/ArrayBuffer.hpp>
#include <optional>
#ifndef testnet
  #include "rust/shield_testnet.h"
#else
  #include "rust/shield_testnet.h"
#endif

namespace margelo::nitro::shield {

class HybridFieldTestnet final : public HybridFieldSpec {
 public:
  HybridFieldTestnet();
  explicit HybridFieldTestnet(rust::Box<shield_testnet::FieldHandle>&& handle);
  ~HybridFieldTestnet() override;

  std::shared_ptr<HybridFieldSpec> fromString(const std::string& value) override;
  std::shared_ptr<HybridFieldSpec> clone() override;
  std::string asString() override;
  std::shared_ptr<ArrayBuffer> toBitsLe() override;
  std::shared_ptr<HybridFieldSpec> multiply(const std::shared_ptr<HybridFieldSpec>& rhs) override;
  std::shared_ptr<HybridFieldSpec> one() override;
  std::shared_ptr<HybridFieldSpec> newDomainSeparator(const std::string& domain) override;

  static std::shared_ptr<HybridFieldSpec> create();

  shield_testnet::FieldHandle& ensureHandle() const;

 private:
  static rust::Box<shield_testnet::FieldHandle> createHandle(const std::string& value);
  static rust::Box<shield_testnet::FieldHandle> cloneHandle(shield_testnet::FieldHandle& handle);
  static rust::Box<shield_testnet::FieldHandle> multiplyHandles(shield_testnet::FieldHandle& lhs, shield_testnet::FieldHandle& rhs);
  static std::shared_ptr<ArrayBuffer> arrayBufferFromBytes(const rust::Vec<uint8_t>& bytes);
  void release();

 private:
  mutable std::optional<rust::Box<shield_testnet::FieldHandle>> handle_;
};

} // namespace margelo::nitro::shield
