// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#include "HybridProgramTestnet.hpp"

#include <stdexcept>
#include <utility>

#ifndef testnet
  #include "rust/shield_testnet.h"
#else
  #include "rust/shield_testnet.h"
#endif

namespace margelo::nitro::shield {

HybridProgramTestnet::HybridProgramTestnet() : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()) {
  auto result = shield_testnet::program_get_credits_program();
  _program = std::make_shared<rust::Box<shield_testnet::ProgramHandle>>(std::move(result));
}

HybridProgramTestnet::HybridProgramTestnet(rust::Box<shield_testnet::ProgramHandle>&& program)
    : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()) {
  _program = std::make_shared<rust::Box<shield_testnet::ProgramHandle>>(std::move(program));
}

shield_testnet::ProgramHandle& HybridProgramTestnet::ensureProgram() const {
  if (!_program) {
    throw std::runtime_error("Program handle is null");
  }
  return **_program;
}

rust::Box<shield_testnet::ProgramHandle>& HybridProgramTestnet::program() {
  if (!_program) {
    throw std::runtime_error("Program handle is null");
  }
  return *_program;
}

const rust::Box<shield_testnet::ProgramHandle>& HybridProgramTestnet::program() const {
  if (!_program) {
    throw std::runtime_error("Program handle is null");
  }
  return *_program;
}

std::shared_ptr<HybridProgramSpec> HybridProgramTestnet::fromString(const std::string& program) {
  auto result = shield_testnet::program_from_string(program.c_str());
  return std::make_shared<HybridProgramTestnet>(std::move(result));
}

std::shared_ptr<HybridProgramSpec> HybridProgramTestnet::clone() {
  auto cloned = ensureProgram().program_clone();
  return std::make_shared<HybridProgramTestnet>(std::move(cloned));
}

std::string HybridProgramTestnet::toString() {
  return ensureProgram().program_to_string().c_str();
}

bool HybridProgramTestnet::hasFunction(const std::string& functionName) {
  return ensureProgram().program_has_function(functionName.c_str());
}

std::vector<std::string> HybridProgramTestnet::convertVec(const rust::Vec<rust::String>& vec) const {
  std::vector<std::string> result;
  result.reserve(vec.size());
  for (const auto& item : vec) {
    result.emplace_back(std::string(item));
  }
  return result;
}

std::vector<std::string> HybridProgramTestnet::getFunctions() {
  return convertVec(ensureProgram().program_get_functions());
}

std::string HybridProgramTestnet::getFunctionInputs(const std::string& functionName) {
  auto result = ensureProgram().program_get_function_inputs(functionName.c_str());
  return std::string(result);
}

std::string HybridProgramTestnet::getMappings() {
  auto result = ensureProgram().program_get_mappings();
  return std::string(result);
}

std::string HybridProgramTestnet::getRecordMembers(const std::string& recordName) {
  auto result = ensureProgram().program_get_record_members(recordName.c_str());

  return std::string(result);
}

std::string HybridProgramTestnet::getStructMembers(const std::string& structName) {
  auto result = ensureProgram().program_get_struct_members(structName.c_str());

  return std::string(result);
}

std::vector<std::string> HybridProgramTestnet::getImports() {
  return convertVec(ensureProgram().program_get_imports());
}

std::string HybridProgramTestnet::id() {
  return ensureProgram().program_id().c_str();
}

std::string HybridProgramTestnet::address() {
  auto result = ensureProgram().program_address();

  return std::string(result);
}

bool HybridProgramTestnet::isEqual(const std::shared_ptr<HybridProgramSpec>& other) {
  auto otherImpl = std::dynamic_pointer_cast<HybridProgramTestnet>(other);
  if (!otherImpl) {
    throw std::runtime_error("Invalid Program instance");
  }
  return ensureProgram().program_is_equal(otherImpl->ensureProgram());
}

std::shared_ptr<HybridProgramSpec> HybridProgramTestnet::create() {
    return std::make_shared<HybridProgramTestnet>();
}

std::shared_ptr<HybridProgramSpec> HybridProgramTestnet::createFromString(const std::string& program) {
  auto result = shield_testnet::program_from_string(program);
  return std::make_shared<HybridProgramTestnet>(std::move(result));
}

void HybridProgramTestnet::getCreditsProgram() {
  auto result = shield_testnet::program_get_credits_program();
  _program = std::make_shared<rust::Box<shield_testnet::ProgramHandle>>(std::move(result));
}

} // namespace margelo::nitro::shield
