// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#include "HybridAddressTestnet.hpp"
#include <cstring>
#include <stdexcept>
#ifndef testnet
#include "rust/shield_testnet.h"
#else
#include "rust/shield_testnet.h"
#endif

namespace margelo::nitro::shield {

// Default constructor
HybridAddressTestnet::HybridAddressTestnet() : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()) {}

// Internal constructor for creating from address handle
HybridAddressTestnet::HybridAddressTestnet(uint64_t addressHandle) : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()), _addressHandle(addressHandle) {}

// Destructor - clean up Rust resources if needed
HybridAddressTestnet::~HybridAddressTestnet() {
  if (_addressHandle != 0) {
    shield_testnet::AddressHandle handle = {_addressHandle};
    shield_testnet::destroy_address(handle);
  }
}

std::shared_ptr<HybridAddressTestnet> HybridAddressTestnet::fromString(const std::string& addressString) {
  uint64_t handle = createAddressHandle(addressString);
  if (handle == 0) {
    throw std::invalid_argument("Invalid address format");
  }
  return std::make_shared<HybridAddressTestnet>(handle);
}

uint64_t HybridAddressTestnet::createAddressHandle(const std::string& addressString) {
  // Validate the address first
  if (!shield_testnet::validate_address(rust::String(addressString))) {
    return 0; // Invalid handle
  }

  // Create the address handle using Rust FFI
  auto handle = shield_testnet::address_from_string(rust::String(addressString));
  return handle.id;
}

std::string HybridAddressTestnet::toString() {
  if (_addressHandle == 0) {
    throw std::runtime_error("Address not initialized - cannot convert to string");
  }
  return rustAddressToString();
}

bool HybridAddressTestnet::verify(const std::shared_ptr<ArrayBuffer>& message, const Signature& signature) {
  if (_addressHandle == 0) {
    throw std::runtime_error("Address not initialized - cannot verify signature");
  }

  uint64_t signatureHandle = extractSignatureHandle(signature);
  return rustAddressVerify(message, signatureHandle);
}

std::string HybridAddressTestnet::rustAddressToString() {
  shield_testnet::AddressHandle handle = {_addressHandle};
  auto result = address_to_string(handle);

  if (!result.success) {
    throw std::runtime_error("Failed to convert address to string: " + std::string(result.error));
  }

  return std::string(result.result);
}

bool HybridAddressTestnet::rustAddressVerify(const std::shared_ptr<ArrayBuffer>& message, uint64_t signatureHandle) {
  if (!message || message->size() == 0) {
    return false;
  }

  shield_testnet::AddressHandle addrHandle = {_addressHandle};
  shield_testnet::SignatureHandle sigHandle = {signatureHandle};

  // Convert ArrayBuffer to rust::Vec
  std::vector<uint8_t> messageVec(message->size());
  std::memcpy(messageVec.data(), message->data(), message->size());
  rust::Vec<uint8_t> rustMessage;
  for (const auto& byte : messageVec) {
    rustMessage.push_back(byte);
  }

  return shield_testnet::address_verify(addrHandle, rustMessage, sigHandle);
}

uint64_t HybridAddressTestnet::extractSignatureHandle(const Signature& signature) {
  // Use the synchronous 'name' field which contains the signature string
  if (signature.name.empty()) {
    throw std::runtime_error("Invalid signature: name is empty");
  }

  auto signatureHandle = shield_testnet::signature_from_string(rust::String(signature.name));

  if (signatureHandle.id == 0) {
    throw std::runtime_error("Invalid signature: failed to parse signature string");
  }

  return signatureHandle.id;
}

} // namespace margelo::nitro::shield
