// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#include "HybridTransactionTestnet.hpp"
#include "HybridFieldTestnet.hpp"

#include "HybridProgramTestnet.hpp"
#include "HybridViewKeyTestnet.hpp"
#include <NitroModules/ArrayBuffer.hpp>
#include <NitroModules/Promise.hpp>
#include <chrono>
#include <cstring>
#include <exception>
#include <stdexcept>
#include <thread>

using namespace margelo::nitro;
using namespace margelo::nitro::shield;

namespace {
struct RecordCiphertextHandleHolder {
  explicit RecordCiphertextHandleHolder(uint64_t value) : id(value) {}
  ~RecordCiphertextHandleHolder() {
    if (id != 0) {
      shield_testnet::RecordCiphertextHandle handle{id};
      shield_testnet::destroy_record_ciphertext(handle);
    }
  }
  uint64_t id;
};

struct RecordPlaintextHandleHolder {
  explicit RecordPlaintextHandleHolder(uint64_t value) : id(value) {}
  ~RecordPlaintextHandleHolder() {
    if (id != 0) {
      shield_testnet::RecordPlaintextHandle handle{id};
      shield_testnet::destroy_record_plaintext(handle);
    }
  }
  uint64_t id;
};

const auto kPromiseWaitTimeout = std::chrono::milliseconds(1000);

std::string waitForPromiseString(const std::shared_ptr<Promise<std::string>>& promise, const std::string& context) {
  if (!promise) {
    throw std::runtime_error(context + ": promise was null");
  }

  auto start = std::chrono::steady_clock::now();
  while (promise->isPending() && std::chrono::steady_clock::now() - start < kPromiseWaitTimeout) {
    std::this_thread::sleep_for(std::chrono::milliseconds(1));
  }

  if (promise->isResolved()) {
    return promise->getResult();
  }

  if (promise->isRejected()) {
    const auto& error = promise->getError();
    if (error) {
      std::rethrow_exception(error);
    }
    throw std::runtime_error(context + ": promise rejected");
  }

  throw std::runtime_error(context + ": promise timed out");
}

} // namespace

namespace margelo::nitro::shield {

HybridTransactionTestnet::HybridTransactionTestnet() : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()), _transaction(nullptr) {}

HybridTransactionTestnet::HybridTransactionTestnet(rust::Box<shield_testnet::TransactionHandle>&& handle) : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()) {
  _transaction = std::make_shared<rust::Box<shield_testnet::TransactionHandle>>(std::move(handle));
}

shield_testnet::TransactionHandle& HybridTransactionTestnet::ensureTransaction() const {
  if (!_transaction) {
    throw std::runtime_error("Transaction handle is null");
  }
  return **_transaction;
}

rust::Box<shield_testnet::TransactionHandle>& HybridTransactionTestnet::transaction() {
  if (!_transaction) {
    throw std::runtime_error("Transaction handle is null");
  }
  return *_transaction;
}

const rust::Box<shield_testnet::TransactionHandle>& HybridTransactionTestnet::transaction() const {
  if (!_transaction) {
    throw std::runtime_error("Transaction handle is null");
  }
  return *_transaction;
}

std::shared_ptr<HybridTransactionSpec> HybridTransactionTestnet::fromString(const std::string& transactionString) {
  auto handle = shield_testnet::transaction_from_string(rust::String(transactionString));
  return std::make_shared<HybridTransactionTestnet>(std::move(handle));
}

void HybridTransactionTestnet::fromBytesLe(const std::shared_ptr<ArrayBuffer>& bytes) {
  if (!bytes) {
    throw std::invalid_argument("Bytes buffer cannot be null");
  }

  rust::Vec<uint8_t> rustBytes;
  rustBytes.reserve(bytes->size());
  const auto* data = static_cast<const uint8_t*>(bytes->data());
  for (size_t i = 0; i < bytes->size(); ++i) {
    rustBytes.push_back(data[i]);
  }

  auto handle = shield_testnet::transaction_from_bytes_le(std::move(rustBytes));
}

std::shared_ptr<HybridTransactionSpec> HybridTransactionTestnet::clone() {
  auto cloned = ensureTransaction().transaction_clone();
  return std::make_shared<HybridTransactionTestnet>(std::move(cloned));
}

std::string HybridTransactionTestnet::toString() {
  return std::string(ensureTransaction().transaction_to_string());
}

std::shared_ptr<ArrayBuffer> HybridTransactionTestnet::toBytesLe() {
  auto result = ensureTransaction().transaction_to_bytes_le();
  if (!result.success) {
    throw std::runtime_error(std::string(result.error));
  }
  return arrayBufferFromBytes(result.bytes);
}

bool HybridTransactionTestnet::containsSerialNumber(const std::shared_ptr<HybridFieldSpec>& serialNumber) {
  auto fieldHybrid = std::dynamic_pointer_cast<HybridFieldTestnet>(serialNumber);
  if (!fieldHybrid) {
    throw std::runtime_error("Transaction.containsSerialNumber expected Field hybrid");
  }
  return ensureTransaction().transaction_contains_serial_number(fieldHybrid->ensureHandle());
}

bool HybridTransactionTestnet::containsCommitment(const std::shared_ptr<HybridFieldSpec>& commitment) {
  auto fieldHybrid = std::dynamic_pointer_cast<HybridFieldTestnet>(commitment);
  if (!fieldHybrid) {
    throw std::runtime_error("Transaction.containsCommitment expected Field hybrid");
  }
  return ensureTransaction().transaction_contains_commitment(fieldHybrid->ensureHandle());
}

std::optional<RecordCiphertext> HybridTransactionTestnet::findRecord(const std::shared_ptr<HybridFieldSpec>& commitment) {
  auto fieldHybrid = std::dynamic_pointer_cast<HybridFieldTestnet>(commitment);
  if (!fieldHybrid) {
    throw std::runtime_error("Transaction.findRecord expected Field hybrid");
  }
  auto result = ensureTransaction().transaction_find_record(fieldHybrid->ensureHandle());

  if (!result.success || result.handle == 0) {
    return std::nullopt;
  }

  return makeRecordCiphertextFromHandle(result.handle);
}

int64_t HybridTransactionTestnet::baseFeeAmount() {
  return static_cast<int64_t>(ensureTransaction().transaction_base_fee_amount());
}

int64_t HybridTransactionTestnet::feeAmount() {
  return static_cast<int64_t>(ensureTransaction().transaction_fee_amount());
}

int64_t HybridTransactionTestnet::priorityFeeAmount() {
  return static_cast<int64_t>(ensureTransaction().transaction_priority_fee_amount());
}

bool HybridTransactionTestnet::isDeploy() {
  return ensureTransaction().transaction_is_deploy();
}

bool HybridTransactionTestnet::isExecute() {
  return ensureTransaction().transaction_is_execute();
}

bool HybridTransactionTestnet::isFee() {
  return ensureTransaction().transaction_is_fee();
}

std::optional<std::shared_ptr<HybridProgramSpec>> HybridTransactionTestnet::deployedProgram() {
  try {
    auto programHandle = ensureTransaction().transaction_deployed_program();
    auto program = std::make_shared<HybridProgramTestnet>(std::move(programHandle));
    return program;
  } catch (const std::exception&) {
    return std::nullopt;
  }
}

std::vector<RecordPlaintext> HybridTransactionTestnet::ownedRecords(const std::shared_ptr<HybridViewKeySpec>& viewKey) {
  auto viewKeyImpl = std::dynamic_pointer_cast<HybridViewKeyTestnet>(viewKey);
  if (!viewKeyImpl) {
    throw std::runtime_error("Invalid ViewKey instance provided to ownedRecords");
  }

  shield_testnet::ViewKeyHandle handle{viewKeyImpl->_viewKeyHandle};
  auto records = ensureTransaction().transaction_owned_records(handle);

  std::vector<RecordPlaintext> result;
  result.reserve(records.size());
  for (auto recordHandle : records) {
    result.push_back(makeRecordPlaintextFromHandle(recordHandle));
  }
  return result;
}

std::vector<TransactionRecord> HybridTransactionTestnet::records() {
  auto entries = ensureTransaction().transaction_records();
  std::vector<TransactionRecord> result;
  result.reserve(entries.size());

  for (auto& entry : entries) {
    auto commitment = std::make_shared<HybridFieldTestnet>(std::move(entry.commitment));
    RecordCiphertext record = makeRecordCiphertextFromHandle(entry.record_handle);
    result.emplace_back(std::move(commitment), record);
  }

  return result;
}

std::string HybridTransactionTestnet::summary() {
  auto result = ensureTransaction().transaction_summary();
  return std::string(result);
}

std::string HybridTransactionTestnet::id() {
  return std::string(ensureTransaction().transaction_id());
}

std::string HybridTransactionTestnet::transactionType() {
  return std::string(ensureTransaction().transaction_type());
}

std::vector<std::string> HybridTransactionTestnet::transitions() {
  return convertVec(ensureTransaction().transaction_transitions());
}

std::vector<TransactionVerifyingKey> HybridTransactionTestnet::verifyingKeys() {
  auto keys = ensureTransaction().transaction_verifying_keys();
  std::vector<TransactionVerifyingKey> result;
  result.reserve(keys.size());
  for (const auto& key : keys) {
    result.emplace_back(std::string(key.program), std::string(key.function), std::string(key.verifying_key), std::string(key.certificate));
  }
  return result;
}

std::shared_ptr<ArrayBuffer> HybridTransactionTestnet::arrayBufferFromBytes(const rust::Vec<uint8_t>& bytes) const {
  auto buffer = ArrayBuffer::allocate(bytes.size());
  if (bytes.size() > 0) {
    std::memcpy(buffer->data(), bytes.data(), bytes.size());
  }
  return buffer;
}

std::vector<std::string> HybridTransactionTestnet::convertVec(const rust::Vec<rust::String>& vec) const {
  std::vector<std::string> result;
  result.reserve(vec.size());
  for (const auto& item : vec) {
    result.emplace_back(std::string(item));
  }
  return result;
}

RecordCiphertext HybridTransactionTestnet::makeRecordCiphertextFromHandle(uint64_t recordHandleId) const {
  auto holder = std::make_shared<RecordCiphertextHandleHolder>(recordHandleId);
  RecordCiphertext ciphertext;
  ciphertext.asString = [holder]() -> std::shared_ptr<Promise<std::string>> {
    shield_testnet::RecordCiphertextHandle handle{holder->id};
    auto result = record_ciphertext_to_string(handle);
    if (!result.success) {
      return Promise<std::string>::rejected(std::make_exception_ptr(std::runtime_error(std::string(result.error))));
    }
    return Promise<std::string>::resolved(std::string(result.result));
  };

  ciphertext.isOwner = [holder](const std::shared_ptr<HybridViewKeySpec>& viewKey) -> std::shared_ptr<Promise<bool>> {
    auto viewKeyImpl = std::dynamic_pointer_cast<HybridViewKeyTestnet>(viewKey);
    if (!viewKeyImpl) {
      return Promise<bool>::rejected(std::make_exception_ptr(std::runtime_error("Invalid ViewKey instance")));
    }
    shield_testnet::RecordCiphertextHandle recordHandle{holder->id};
    shield_testnet::ViewKeyHandle viewKeyHandle{viewKeyImpl->_viewKeyHandle};
    bool owner = record_ciphertext_is_owner(recordHandle, viewKeyHandle);
    return Promise<bool>::resolved(std::move(owner));
  };

  return ciphertext;
}

RecordPlaintext HybridTransactionTestnet::makeRecordPlaintextFromHandle(uint64_t recordHandleId) const {
  auto holder = std::make_shared<RecordPlaintextHandleHolder>(recordHandleId);
  RecordPlaintext plaintext;
  plaintext.asString = [holder]() -> std::shared_ptr<Promise<std::string>> {
    shield_testnet::RecordPlaintextHandle handle{holder->id};
    auto result = record_plaintext_to_string(handle);
    if (!result.success) {
      return Promise<std::string>::rejected(std::make_exception_ptr(std::runtime_error(std::string(result.error))));
    }
    return Promise<std::string>::resolved(std::string(result.result));
  };
  return plaintext;
}

std::shared_ptr<HybridTransactionSpec> HybridTransactionTestnet::create() {
  throw std::runtime_error("Transaction cannot be created without initial data");
}

std::shared_ptr<HybridTransactionSpec> HybridTransactionTestnet::createFromString(const std::string& transactionString) {
  auto handle = shield_testnet::transaction_from_string(rust::String(transactionString));
  return std::make_shared<HybridTransactionTestnet>(std::move(handle));
}

} // namespace margelo::nitro::shield
