// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#pragma once

#include "HybridAuthorizationSpec.hpp"
#include "HybridPrivateKeySpec.hpp"
#include "HybridProgramManagerSpec.hpp"
#include "HybridProgramSpec.hpp"
#include "HybridProvingRequestSpec.hpp"
#include "HybridTransactionSpec.hpp"
#include "RecordPlaintext.hpp"
#include <NitroModules/Null.hpp>
#include <NitroModules/Promise.hpp>
#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <variant>
#include <vector>

namespace margelo::nitro::shield {

class HybridProgramManagerTestnet : public HybridProgramManagerSpec {
 public:
  explicit HybridProgramManagerTestnet() : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()) {}

  // Build an authorization for program execution
  std::shared_ptr<HybridAuthorizationSpec>
  buildAuthorization(const std::string& programName, const std::string& functionName, const std::vector<std::string>& inputs,
                     const std::shared_ptr<HybridPrivateKeySpec>& privateKey, const std::string& programSource,
                     const std::unordered_map<std::string, std::string>& programImports, double edition) override;

  // Build a fee authorization for transactions
  std::shared_ptr<HybridAuthorizationSpec> buildFeeAuthorization(const std::string& deploymentOrExecutionId, int64_t baseFeeCredits,
                                                                 int64_t priorityFeeCredits,
                                                                 const std::shared_ptr<HybridPrivateKeySpec>& privateKey,
                                                                 const std::string& feeRecord) override;

  // Estimate minimum execution fee (microcredits)
  int64_t estimateExecutionFee(const std::string& program, const std::optional<std::string>& functionName,
                               const std::optional<std::unordered_map<std::string, std::string>>& imports,
                               std::optional<double> edition) override;

  // Estimate minimum execution fee (microcredits)
  int64_t estimateFeeForAuthorization(const std::string& programSource,
                                      const std::optional<std::shared_ptr<HybridAuthorizationSpec>>& authorization,
                                      const std::optional<std::unordered_map<std::string, std::string>>& imports,
                                      std::optional<double> edition) override;

  // Estimate minimum deployment fee (microcredits)
  int64_t estimateDeploymentFee(const std::string& programString, const std::unordered_map<std::string, std::string>& imports) override;

  // Build a deployment transaction
  std::shared_ptr<HybridTransactionSpec>
  buildDeploymentTransaction(const std::shared_ptr<HybridPrivateKeySpec>& privateKey, const std::string& program, int64_t priorityFee,
                             const std::optional<RecordPlaintext>& feeRecord, const std::string& url,
                             const std::unordered_map<std::string, std::variant<std::shared_ptr<HybridProgramSpec>, std::string>>& imports,
                             const std::shared_ptr<HybridProvingKeySpec>& feeProvingKey,
                             const std::shared_ptr<HybridVerifyingKeySpec>& verifyingKey,
                             const std::optional<std::shared_ptr<HybridOfflineQuerySpec>>& offlineQuery) override;

  // Build a complete execution transaction (matches Nitro spec)
  std::shared_ptr<Promise<std::shared_ptr<HybridTransactionSpec>>> buildExecutionTransaction(
      const std::shared_ptr<HybridPrivateKeySpec>& privateKey, const std::string& program, const std::string& functionName,
      const std::vector<std::string>& inputs, int64_t priorityFee, const std::optional<RecordPlaintext>& feeRecord,
      const std::optional<std::string>& url,
      const std::optional<std::unordered_map<std::string, std::variant<std::shared_ptr<HybridProgramSpec>, std::string>>>& imports,
      const std::optional<std::shared_ptr<HybridProvingKeySpec>>& provingKey,
      const std::optional<std::shared_ptr<HybridVerifyingKeySpec>>& verifyingKey,
      const std::optional<std::shared_ptr<HybridProvingKeySpec>>& feeProvingKey,
      const std::optional<std::shared_ptr<HybridVerifyingKeySpec>>& feeVerifyingKey,
      const std::optional<std::shared_ptr<HybridOfflineQuerySpec>>& offlineQuery, std::optional<double> edition) override;

  std::shared_ptr<Promise<std::shared_ptr<HybridProvingRequestSpec>>>
  buildProvingRequest(const std::shared_ptr<HybridPrivateKeySpec>& privateKey, const std::string& program, const std::string& functionName,
                      const std::vector<std::string>& inputs, int64_t baseFeeCredits, int64_t priorityFeeCredits,
                      const std::optional<std::variant<nitro::NullType, RecordPlaintext>>& feeRecord,
                      const std::unordered_map<std::string, std::string>& imports, bool broadcast, bool unchecked, double edition,
                      bool useFeeMaster) override;

  // Load inclusion prover key
  void loadInclusionProver(const std::shared_ptr<HybridProvingKeySpec>& provingKey) override;

  // Compute the commitment for a record plaintext (needed for state path fetching)
  std::string recordPlaintextToCommitment(const std::string& recordPlaintext, const std::string& programId, const std::string& recordName,
                                          const std::shared_ptr<HybridViewKeySpec>& viewKey) override;

  // Compute the serial number for a record plaintext (needed for spent checking)
  std::string recordPlaintextToSerialNumber(const std::string& recordPlaintext, const std::shared_ptr<HybridPrivateKeySpec>& privateKey,
                                            const std::string& programId, const std::string& recordName,
                                            const std::string& recordViewKey) override;

 private:
  // Helper methods for validation
  void validateInputs(const std::string& programName, const std::string& functionName, const std::vector<std::string>& inputs) const;

  void validatePrivateKey(const std::shared_ptr<HybridPrivateKeySpec>& privateKey) const;
};

} // namespace margelo::nitro::shield