// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#include "HybridFieldTestnet.hpp"

#include <cstring>
#include <stdexcept>

namespace margelo::nitro::shield {

HybridFieldTestnet::HybridFieldTestnet() : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()), handle_(std::nullopt) {}

HybridFieldTestnet::HybridFieldTestnet(rust::Box<shield_testnet::FieldHandle>&& handle)
    : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()), handle_(std::move(handle)) {}

HybridFieldTestnet::~HybridFieldTestnet() {
  release();
}

std::shared_ptr<HybridFieldSpec> HybridFieldTestnet::create() {
  return std::make_shared<HybridFieldTestnet>();
}

std::shared_ptr<HybridFieldSpec> HybridFieldTestnet::fromString(const std::string& value) {
  return std::make_shared<HybridFieldTestnet>(createHandle(value));
}

std::shared_ptr<HybridFieldSpec> HybridFieldTestnet::clone() {
  auto cloned = cloneHandle(ensureHandle());
  return std::make_shared<HybridFieldTestnet>(std::move(cloned));
}

std::string HybridFieldTestnet::asString() {
  auto result = ensureHandle().field_to_string();
  return std::string(result);
}

std::shared_ptr<ArrayBuffer> HybridFieldTestnet::toBitsLe() {
  auto result = ensureHandle().field_to_bits_le_handle();
  if (!result.success) {
    throw std::runtime_error(std::string(result.error));
  }
  return arrayBufferFromBytes(result.bytes);
}

std::shared_ptr<HybridFieldSpec> HybridFieldTestnet::multiply(const std::shared_ptr<HybridFieldSpec>& rhs) {
  auto rhsField = std::dynamic_pointer_cast<HybridFieldTestnet>(rhs);
  if (!rhsField) {
    throw std::runtime_error("Expected HybridFieldTestnet instance for multiply()");
  }
  auto resultHandle = multiplyHandles(ensureHandle(), rhsField->ensureHandle());
  return std::make_shared<HybridFieldTestnet>(std::move(resultHandle));
}

std::shared_ptr<HybridFieldSpec> HybridFieldTestnet::one() {
  auto handle = shield_testnet::field_one();
  return std::make_shared<HybridFieldTestnet>(std::move(handle));
}

std::shared_ptr<HybridFieldSpec> HybridFieldTestnet::newDomainSeparator(const std::string& domain) {
  auto handle = shield_testnet::field_new_domain_separator(rust::String(domain));
  return std::make_shared<HybridFieldTestnet>(std::move(handle));
}

shield_testnet::FieldHandle& HybridFieldTestnet::ensureHandle() const {
  if (!handle_.has_value()) {
    throw std::runtime_error("Field handle is not initialized");
  }
  return **handle_;
}

rust::Box<shield_testnet::FieldHandle> HybridFieldTestnet::createHandle(const std::string& value) {
    auto handle = shield_testnet::field_from_string(rust::String(value));
  return handle;
}

rust::Box<shield_testnet::FieldHandle> HybridFieldTestnet::cloneHandle(shield_testnet::FieldHandle& handle) {
  auto result = handle.field_clone();
  return result;
}

rust::Box<shield_testnet::FieldHandle> HybridFieldTestnet::multiplyHandles(shield_testnet::FieldHandle& lhs, shield_testnet::FieldHandle& rhs) {
  auto result = lhs.field_multiply_handles(rhs);
  return result;
}

std::shared_ptr<ArrayBuffer> HybridFieldTestnet::arrayBufferFromBytes(const rust::Vec<uint8_t>& bytes) {
  auto buffer = ArrayBuffer::allocate(bytes.size());
  if (bytes.size() > 0) {
    std::memcpy(buffer->data(), bytes.data(), bytes.size());
  }
  return buffer;
}

void HybridFieldTestnet::release() {
  if (handle_.has_value()) {
    handle_.reset();
  }
}

} // namespace margelo::nitro::shield
