// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#include "HybridGroupTestnet.hpp"

#include <stdexcept>

namespace margelo::nitro::shield {

HybridGroupTestnet::HybridGroupTestnet() : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()), handle_(std::nullopt) {}

HybridGroupTestnet::HybridGroupTestnet(rust::Box<shield_testnet::GroupHandle>&& handle)
    : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()), handle_(std::move(handle)) {}

HybridGroupTestnet::~HybridGroupTestnet() {
  release();
}

std::shared_ptr<HybridGroupSpec> HybridGroupTestnet::create() {
  return std::make_shared<HybridGroupTestnet>();
}

std::shared_ptr<HybridGroupSpec> HybridGroupTestnet::fromString(const std::string& value) {
  return std::make_shared<HybridGroupTestnet>(createHandle(value));
}

std::shared_ptr<HybridGroupSpec> HybridGroupTestnet::clone() {
  auto cloned = cloneHandle(ensureHandle());
  return std::make_shared<HybridGroupTestnet>(std::move(cloned));
}

std::string HybridGroupTestnet::toString() {
  auto result = ensureHandle().group_to_string();
  return std::string(result);
}

shield_testnet::GroupHandle& HybridGroupTestnet::ensureHandle() const {
  if (!handle_.has_value()) {
    throw std::runtime_error("Group handle is not initialized");
  }
  return **handle_;
}

rust::Box<shield_testnet::GroupHandle> HybridGroupTestnet::createHandle(const std::string& value) {
  auto handle = shield_testnet::group_from_string(rust::String(value));
  return handle;
}

rust::Box<shield_testnet::GroupHandle> HybridGroupTestnet::cloneHandle(shield_testnet::GroupHandle& handle) {
  auto result = handle.group_clone();
  return result;
}

void HybridGroupTestnet::release() {
  if (handle_.has_value()) {
    handle_.reset();
  }
}

} // namespace margelo::nitro::shield
