// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#include "HybridProvingKeyTestnet.hpp"
#include <cstring>

namespace margelo::nitro::shield {

HybridProvingKeyTestnet::~HybridProvingKeyTestnet() {
  if (_handle != 0) {
    shield_testnet::ProvingKeyHandle handle = {_handle};
    shield_testnet::destroy_proving_key(handle);
  }
}

std::shared_ptr<ArrayBuffer> HybridProvingKeyTestnet::toBytes() {
  if (_handle == 0)
    return ArrayBuffer::allocate(0);
  shield_testnet::ProvingKeyHandle handle = {_handle};
  auto res = shield_testnet::proving_key_to_bytes(handle);
  if (!res.success) {
    throw std::runtime_error(std::string("proving_key_to_bytes failed: ") + std::string(res.error));
  }
  auto buf = ArrayBuffer::allocate(res.bytes.size());
  std::memcpy(buf->data(), res.bytes.data(), res.bytes.size());
  return buf;
}

void HybridProvingKeyTestnet::initWithBytes(const std::shared_ptr<ArrayBuffer>& bytes) {
  if (!bytes)
    throw std::invalid_argument("bytes is null");
  rust::Vec<uint8_t> rustBytes;
  rustBytes.reserve(bytes->size());
  auto ptr = static_cast<const uint8_t*>(bytes->data());
  for (size_t i = 0; i < bytes->size(); i++)
    rustBytes.push_back(ptr[i]);
  auto res = shield_testnet::proving_key_from_bytes(rustBytes);
  if (!res.success) {
    throw std::runtime_error(std::string("proving_key_from_bytes failed: ") + std::string(res.error));
  }
  _handle = res.handle;
}

void HybridProvingKeyTestnet::initWithString(const std::string& key) {
  auto res = shield_testnet::proving_key_from_string(rust::String(key));
  if (!res.success) {
    throw std::runtime_error(std::string("proving_key_from_string failed: ") + std::string(res.error));
  }
  _handle = res.handle;
}

std::string HybridProvingKeyTestnet::checksum() {
  if (_handle == 0)
    return "";
  shield_testnet::ProvingKeyHandle handle = {_handle};
  auto res = shield_testnet::proving_key_checksum(handle);
  if (!res.success) {
    throw std::runtime_error(std::string("proving_key_checksum failed: ") + std::string(res.error));
  }
  return std::string(res.result);
}

std::shared_ptr<HybridProvingKeySpec> HybridProvingKeyTestnet::copy() {
  if (_handle == 0)
    return std::make_shared<HybridProvingKeyTestnet>();
  shield_testnet::ProvingKeyHandle handle = {_handle};
  auto res = shield_testnet::proving_key_copy(handle);
  if (!res.success) {
    throw std::runtime_error(std::string("proving_key_copy failed: ") + std::string(res.error));
  }
  auto instance = std::make_shared<HybridProvingKeyTestnet>();
  instance->_handle = res.handle;
  return instance;
}

bool HybridProvingKeyTestnet::isBondPublicProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_bond_public_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isBondValidatorProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_bond_validator_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isClaimUnbondPublicProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_claim_unbond_public_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isFeePrivateProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_fee_private_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isFeePublicProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_fee_public_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isInclusionProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_inclusion_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isJoinProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_join_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isSetValidatorStateProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_set_validator_state_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isSplitProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_split_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isTransferPrivateProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_transfer_private_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isTransferPrivateToPublicProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_transfer_private_to_public_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isTransferPublicProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_transfer_public_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isTransferPublicAsSignerProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_transfer_public_as_signer_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isTransferPublicToPrivateProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_transfer_public_to_private_prover_with_metadata(handle, rust::String(metadataJson));
}
bool HybridProvingKeyTestnet::isUnbondPublicProver(const std::string& metadataJson) {
  if (_handle == 0)
    return false;
  shield_testnet::ProvingKeyHandle handle = {_handle};
  return shield_testnet::proving_key_is_unbond_public_prover_with_metadata(handle, rust::String(metadataJson));
}

} // namespace margelo::nitro::shield
