// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#include "HybridPrivateKeyTestnet.hpp"
#include "HybridAddressTestnet.hpp"
#include "HybridViewKeyTestnet.hpp"
#include <cstring>
#include <stdexcept>
#ifndef testnet
#include "rust/shield_testnet.h"
#else
#include "rust/shield_testnet.h"
#endif

namespace margelo::nitro::shield {

// Default constructor
HybridPrivateKeyTestnet::HybridPrivateKeyTestnet() : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()) {}

// Internal constructor for creating from private key handle
HybridPrivateKeyTestnet::HybridPrivateKeyTestnet(uint64_t privateKeyHandle) : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()), _privateKeyHandle(privateKeyHandle) {}

// Destructor - clean up Rust resources if needed
HybridPrivateKeyTestnet::~HybridPrivateKeyTestnet() {
  if (_privateKeyHandle != 0) {
    shield_testnet::PrivateKeyHandle handle = {_privateKeyHandle};
    shield_testnet::destroy_private_key(handle);
  }
}

std::shared_ptr<HybridPrivateKeyTestnet> HybridPrivateKeyTestnet::fromString(const std::string& privateKeyString) {
  uint64_t handle = createPrivateKeyHandle(privateKeyString);
  if (handle == 0) {
    throw std::invalid_argument("Invalid private key format");
  }
  return std::make_shared<HybridPrivateKeyTestnet>(handle);
}

std::shared_ptr<HybridPrivateKeyTestnet> HybridPrivateKeyTestnet::fromSeed(const std::shared_ptr<ArrayBuffer>& seed) {
  uint64_t handle = createPrivateKeyFromSeed(seed);
  if (handle == 0) {
    throw std::invalid_argument("Invalid seed for private key generation");
  }
  return std::make_shared<HybridPrivateKeyTestnet>(handle);
}

std::shared_ptr<HybridPrivateKeyTestnet> HybridPrivateKeyTestnet::generate() {
  uint64_t handle = generatePrivateKey();
  if (handle == 0) {
    throw std::runtime_error("Failed to generate private key");
  }
  return std::make_shared<HybridPrivateKeyTestnet>(handle);
}

uint64_t HybridPrivateKeyTestnet::createPrivateKeyHandle(const std::string& privateKeyString) {
  // Validate the private key first
  if (!shield_testnet::validate_private_key(rust::String(privateKeyString))) {
    return 0; // Invalid handle
  }

  // Create the private key handle using Rust FFI
  auto handle = shield_testnet::private_key_from_string(rust::String(privateKeyString));
  return handle.id;
}

uint64_t HybridPrivateKeyTestnet::createPrivateKeyFromSeed(const std::shared_ptr<ArrayBuffer>& seed) {
  if (!seed || seed->size() != 32) {
    return 0; // Invalid seed
  }

  // Convert ArrayBuffer to rust::Vec
  std::vector<uint8_t> seedVec(seed->size());
  std::memcpy(seedVec.data(), seed->data(), seed->size());
  rust::Vec<uint8_t> rustSeed;
  for (const auto& byte : seedVec) {
    rustSeed.push_back(byte);
  }

  // Create the private key handle using Rust FFI
  auto handle = shield_testnet::private_key_from_seed_unchecked(rustSeed);
  return handle.id;
}

uint64_t HybridPrivateKeyTestnet::generatePrivateKey() {
  // Generate a new private key using Rust FFI
  auto handle = shield_testnet::create_private_key();
  return handle.id;
}

std::string HybridPrivateKeyTestnet::toString() {
  if (_privateKeyHandle == 0) {
    throw std::runtime_error("Private key not initialized - cannot convert to string");
  }
  return rustPrivateKeyToString();
}

std::shared_ptr<HybridAddressSpec> HybridPrivateKeyTestnet::toAddress() {
  if (_privateKeyHandle == 0) {
    throw std::runtime_error("Private key not initialized - cannot derive address");
  }
  uint64_t addressHandle = rustPrivateKeyToAddress();
  return std::make_shared<HybridAddressTestnet>(addressHandle);
}

std::shared_ptr<HybridViewKeySpec> HybridPrivateKeyTestnet::toViewKey() {
  if (_privateKeyHandle == 0) {
    throw std::runtime_error("Private key not initialized - cannot derive view key");
  }
  uint64_t viewKeyHandle = rustPrivateKeyToViewKey();
  return std::make_shared<HybridViewKeyTestnet>(viewKeyHandle);
}

ComputeKey HybridPrivateKeyTestnet::toComputeKey() {
  if (_privateKeyHandle == 0) {
    throw std::runtime_error("Private key not initialized - cannot derive compute key");
  }
  return rustPrivateKeyToComputeKey();
}

Signature HybridPrivateKeyTestnet::sign(const std::shared_ptr<ArrayBuffer>& message) {
  if (_privateKeyHandle == 0) {
    throw std::runtime_error("Private key not initialized - cannot sign message");
  }
  return rustPrivateKeySign(message);
}

std::string HybridPrivateKeyTestnet::rustPrivateKeyToString() {
  shield_testnet::PrivateKeyHandle handle = {_privateKeyHandle};
  auto result = shield_testnet::private_key_to_string(handle);

  if (!result.success) {
    throw std::runtime_error("Failed to convert private key to string: " + std::string(result.error));
  }

  return std::string(result.result);
}

uint64_t HybridPrivateKeyTestnet::rustPrivateKeyToAddress() {
  shield_testnet::PrivateKeyHandle handle = {_privateKeyHandle};
  auto addressHandle = shield_testnet::private_key_to_address(handle);
  return addressHandle.id;
}

uint64_t HybridPrivateKeyTestnet::rustPrivateKeyToViewKey() {
  shield_testnet::PrivateKeyHandle handle = {_privateKeyHandle};
  auto viewKeyHandle = shield_testnet::private_key_to_view_key(handle);
  return viewKeyHandle.id;
}

ComputeKey HybridPrivateKeyTestnet::rustPrivateKeyToComputeKey() {
  shield_testnet::PrivateKeyHandle handle = {_privateKeyHandle};
  auto computeKeyHandle = shield_testnet::private_key_to_compute_key(handle);

  // Create ComputeKey struct with handle - make synchronous
  ComputeKey computeKey;
  auto result = shield_testnet::compute_key_to_string(computeKeyHandle);

  // Destroy the temporary handle to prevent memory leak
  shield_testnet::destroy_compute_key(computeKeyHandle);

  if (!result.success) {
    throw std::runtime_error("Failed to convert compute key to string: " + std::string(result.error));
  }

  std::string computeKeyString = std::string(result.result);
  computeKey.asString = [computeKeyString]() mutable -> std::shared_ptr<Promise<std::string>> {
    return Promise<std::string>::resolved(std::move(computeKeyString));
  };

  return computeKey;
}

Signature HybridPrivateKeyTestnet::rustPrivateKeySign(const std::shared_ptr<ArrayBuffer>& message) {
  if (!message || message->size() == 0) {
    throw std::invalid_argument("Message cannot be empty");
  }

  shield_testnet::PrivateKeyHandle handle = {_privateKeyHandle};

  // Convert ArrayBuffer to rust::Vec
  std::vector<uint8_t> messageVec(message->size());
  std::memcpy(messageVec.data(), message->data(), message->size());
  rust::Vec<uint8_t> rustMessage;
  for (const auto& byte : messageVec) {
    rustMessage.push_back(byte);
  }

  auto result = shield_testnet::private_key_sign(handle, rustMessage);

  if (!result.success) {

    throw std::runtime_error("Failed to sign message: " + std::string(result.error));
  }

  // Create Signature struct from result
  Signature signature;
  // Get the actual signature string from Rust immediately (synchronous)
  shield_testnet::SignatureHandle signatureHandle = {result.signature_handle};
  auto signatureResult = shield_testnet::signature_to_string(signatureHandle);

  // Destroy the temporary handle to prevent memory leak
  shield_testnet::destroy_signature(signatureHandle);

  if (!signatureResult.success) {
    throw std::runtime_error("Failed to convert signature to string: " + std::string(signatureResult.error));
  }

  std::string signatureString = std::string(signatureResult.result);

  // Store the signature string in the name field for synchronous access during verification
  signature.name = signatureString;

  // Store the original signature string and return it synchronously via lambda
  signature.asString = [signatureString]() mutable -> std::shared_ptr<Promise<std::string>> {
    return Promise<std::string>::resolved(std::move(signatureString));
  };

  return signature;
}

// Static factory methods for creating HybridPrivateKeyTestnet instances from TypeScript
std::shared_ptr<HybridPrivateKeySpec> HybridPrivateKeyTestnet::create() {
  return generate();
}

std::shared_ptr<HybridPrivateKeySpec> HybridPrivateKeyTestnet::createFromString(const std::string& privateKeyString) {
  return fromString(privateKeyString);
}

std::shared_ptr<HybridPrivateKeySpec> HybridPrivateKeyTestnet::createFromSeed(const std::shared_ptr<ArrayBuffer>& seed) {
  return fromSeed(seed);
}

} // namespace margelo::nitro::shield
