// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#pragma once

#include "HybridScalarSpec.hpp"
#include <optional>
#ifndef testnet
  #include "rust/shield_testnet.h"
#else
  #include "rust/shield_testnet.h"
#endif

namespace margelo::nitro::shield {

class HybridScalarTestnet final : public HybridScalarSpec {
 public:
  HybridScalarTestnet();
  explicit HybridScalarTestnet(rust::Box<shield_testnet::ScalarHandle>&& handle);
  ~HybridScalarTestnet() override;

  std::shared_ptr<HybridScalarSpec> fromString(const std::string& value) override;
  std::shared_ptr<HybridScalarSpec> clone() override;
  std::string toString() override;

  static std::shared_ptr<HybridScalarSpec> create();

 private:
  shield_testnet::ScalarHandle& ensureHandle() const;
  static rust::Box<shield_testnet::ScalarHandle> createHandle(const std::string& value);
  static rust::Box<shield_testnet::ScalarHandle> cloneHandle(shield_testnet::ScalarHandle& handle);
  void release();

 private:
  mutable std::optional<rust::Box<shield_testnet::ScalarHandle>> handle_;
};

} // namespace margelo::nitro::shield
