// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#pragma once

#include "HybridAuthorizationSpec.hpp"
#include "HybridProvingRequestSpec.hpp"
#include <NitroModules/ArrayBuffer.hpp>
#include <optional>
#include <cstdint>
#include <memory>
#include <string>


namespace margelo::nitro::shield {

class HybridProvingRequestTestnet : public HybridProvingRequestSpec {
 public:
  explicit HybridProvingRequestTestnet() : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()) {}
  ~HybridProvingRequestTestnet();

  // Factory methods
  // Match base Spec (3-arg) signature
  std::shared_ptr<HybridProvingRequestSpec> create(
    const std::shared_ptr<HybridAuthorizationSpec>& authorization,
    const std::optional<std::shared_ptr<HybridAuthorizationSpec>>& feeAuthorization,
    bool broadcast
  ) override;
  // Convenience overload with fee authorization (non-override)
  std::shared_ptr<HybridProvingRequestSpec> createWithFee(const std::shared_ptr<HybridAuthorizationSpec>& authorization, const std::optional<std::shared_ptr<HybridAuthorizationSpec>>& feeAuthorization, bool broadcast);
  std::shared_ptr<HybridProvingRequestSpec> fromString(const std::string& request) override;
  std::shared_ptr<HybridProvingRequestSpec> fromBytesLe(const std::shared_ptr<ArrayBuffer>& bytes) override;
  std::shared_ptr<HybridProvingRequestSpec>
  fromAuthorizations(const std::shared_ptr<HybridAuthorizationSpec>& authorization,
                     const std::optional<std::shared_ptr<HybridAuthorizationSpec>>& feeAuthorization, bool broadcast);

  // Serialization methods
  std::string toString();
  std::shared_ptr<ArrayBuffer> toBytesLe() override;
  ProvingRequestJSON toJSON() override;

  // Accessors - these match the pure virtual methods from spec
  std::shared_ptr<HybridAuthorizationSpec> authorization() override;
  std::optional<std::shared_ptr<HybridAuthorizationSpec>> feeAuthorization() override;
  bool broadcast() override;

  // Utility methods
  std::shared_ptr<HybridProvingRequestSpec> replicate() override;
  bool verify() override;
  bool isEqual(const std::shared_ptr<HybridProvingRequestSpec>& other) override;

  // Internal constructor for creating from proving request handle
  explicit HybridProvingRequestTestnet(uint64_t provingRequestHandle);

 private:
  // Internal state
  uint64_t _provingRequestHandle = 0;
};

} // namespace margelo::nitro::shield