// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#include "HybridViewKeyTestnet.hpp"
#include "HybridAddressTestnet.hpp"
#include "HybridFieldTestnet.hpp"
#include <NitroModules/ArrayBuffer.hpp>
#include <NitroModules/Promise.hpp>
#include <cstring>
#include <stdexcept>
#ifndef testnet
#include "rust/shield_testnet.h"
#else
#include "rust/shield_testnet.h"
#endif

namespace margelo::nitro::shield {

// Default constructor
HybridViewKeyTestnet::HybridViewKeyTestnet() : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()) {}

// Internal constructor for creating from view key handle
HybridViewKeyTestnet::HybridViewKeyTestnet(uint64_t viewKeyHandle) : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()), _viewKeyHandle(viewKeyHandle) {}

// Destructor - clean up Rust resources if needed
HybridViewKeyTestnet::~HybridViewKeyTestnet() {
  if (_viewKeyHandle != 0) {
    shield_testnet::ViewKeyHandle handle = {_viewKeyHandle};
    shield_testnet::destroy_view_key(handle);
  }
}

std::shared_ptr<HybridViewKeyTestnet> HybridViewKeyTestnet::fromString(const std::string& viewKeyString) {
  uint64_t handle = createViewKeyHandle(viewKeyString);
  if (handle == 0) {
    throw std::invalid_argument("Invalid view key format");
  }
  return std::make_shared<HybridViewKeyTestnet>(handle);
}

uint64_t HybridViewKeyTestnet::createViewKeyHandle(const std::string& viewKeyString) {
  // Validate the view key first
  if (!shield_testnet::validate_view_key(rust::String(viewKeyString))) {
    return 0; // Invalid handle
  }

  // Create the view key handle using Rust FFI
  auto handle = shield_testnet::view_key_from_string(rust::String(viewKeyString));
  return handle.id;
}

std::string HybridViewKeyTestnet::toString() {
  if (_viewKeyHandle == 0) {
    throw std::runtime_error("View key not initialized - cannot convert to string");
  }
  return rustViewKeyToString();
}

std::shared_ptr<HybridAddressSpec> HybridViewKeyTestnet::toAddress() {
  if (_viewKeyHandle == 0) {
    throw std::runtime_error("View key not initialized - cannot derive address");
  }
  uint64_t addressHandle = rustViewKeyToAddress();
  return std::make_shared<HybridAddressTestnet>(addressHandle);
}

RecordPlaintext HybridViewKeyTestnet::decrypt(const std::string& ciphertext) {
  if (_viewKeyHandle == 0) {
    throw std::runtime_error("View key not initialized - cannot decrypt record");
  }
  return rustViewKeyDecrypt(ciphertext);
}

std::shared_ptr<HybridFieldSpec> HybridViewKeyTestnet::toField() {
  if (_viewKeyHandle == 0) {
    throw std::runtime_error("View key not initialized - cannot convert to field");
  }
  auto fieldHandle = rustViewKeyToField();
  return std::make_shared<HybridFieldTestnet>(std::move(fieldHandle));
}

std::shared_ptr<ArrayBuffer> HybridViewKeyTestnet::toBytesLe() {
  if (_viewKeyHandle == 0) {
    throw std::runtime_error("View key not initialized - cannot convert to bytes");
  }

  auto bytes = rustViewKeyToBytesLe();
  auto buffer = ArrayBuffer::allocate(bytes.size());
  if (bytes.size() > 0) {
    std::memcpy(buffer->data(), bytes.data(), bytes.size());
  }
  return buffer;
}

std::shared_ptr<HybridViewKeySpec> HybridViewKeyTestnet::fromBytesLe(const std::shared_ptr<ArrayBuffer>& bytes) {
  rust::Vec<uint8_t> bytesVec;
  bytesVec.reserve(bytes->size());
  for (size_t i = 0; i < bytes->size(); ++i) {
    bytesVec.push_back(bytes->data()[i]);
  }

  auto handle = shield_testnet::view_key_from_bytes_le(std::move(bytesVec));
  if (handle.id == 0) {
    throw std::runtime_error("Invalid view key bytes");
  }

  return std::make_shared<HybridViewKeyTestnet>(handle.id);
}

std::string HybridViewKeyTestnet::rustViewKeyToString() {
  shield_testnet::ViewKeyHandle handle = {_viewKeyHandle};
  auto result = shield_testnet::view_key_to_string(handle);

  if (!result.success) {
    throw std::runtime_error("Failed to convert view key to string: " + std::string(result.error));
  }

  return std::string(result.result);
}

uint64_t HybridViewKeyTestnet::rustViewKeyToAddress() {
  shield_testnet::ViewKeyHandle handle = {_viewKeyHandle};
  auto addressHandle = shield_testnet::view_key_to_address(handle);
  return addressHandle.id;
}

RecordPlaintext HybridViewKeyTestnet::rustViewKeyDecrypt(const std::string& ciphertext) {
  shield_testnet::ViewKeyHandle handle = {_viewKeyHandle};
  auto result = shield_testnet::view_key_decrypt(handle, rust::String(ciphertext));

  if (!result.success) {
    throw std::runtime_error("Failed to decrypt record: " + std::string(result.error));
  }

  // Convert to string immediately and destroy handle to prevent memory leak
  shield_testnet::RecordPlaintextHandle plaintextHandle = {result.handle};
  auto plaintextResult = shield_testnet::record_plaintext_to_string(plaintextHandle);

  // Destroy the temporary handle to prevent memory leak
  shield_testnet::destroy_record_plaintext(plaintextHandle);

  if (!plaintextResult.success) {
    throw std::runtime_error("Failed to convert plaintext to string: " + std::string(plaintextResult.error));
  }

  std::string plaintextString = std::string(plaintextResult.result);

  // Create RecordPlaintext struct with the pre-converted string
  RecordPlaintext plaintext;
  plaintext.asString = [plaintextString]() mutable -> std::shared_ptr<Promise<std::string>> {
    return Promise<std::string>::resolved(std::move(plaintextString));
  };

  return plaintext;
}

rust::Box<shield_testnet::FieldHandle> HybridViewKeyTestnet::rustViewKeyToField() {
  shield_testnet::ViewKeyHandle handle = {_viewKeyHandle};
  return shield_testnet::view_key_to_field(handle);
}

rust::Vec<uint8_t> HybridViewKeyTestnet::rustViewKeyToBytesLe() {
  shield_testnet::ViewKeyHandle handle = {_viewKeyHandle};
  return shield_testnet::view_key_to_bytes_le(handle);
}

// Static factory methods for creating HybridViewKeyTestnet instances from TypeScript
std::shared_ptr<HybridViewKeySpec> HybridViewKeyTestnet::create() {
  // ViewKey cannot be generated directly - it must be derived from a private key
  // For now, throw an error - this should not be called directly
  throw std::runtime_error("ViewKey cannot be created directly - derive from PrivateKey instead");
}

std::shared_ptr<HybridViewKeySpec> HybridViewKeyTestnet::createFromString(const std::string& viewKeyString) {
  return fromString(viewKeyString);
}

} // namespace margelo::nitro::shield
