// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#pragma once

#include "HybridNetworkSpec.hpp"
#include <NitroModules/ArrayBuffer.hpp>
#include <memory>
#include <string>
#include <vector>

namespace margelo::nitro::shield {

class HybridNetworkTestnet : public HybridNetworkSpec {
 public:
  explicit HybridNetworkTestnet() : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()) {}

  NetworkName getNetwork() override;
  void setNetwork(NetworkName network) override;

  static std::string getNetworkStatic();
};

} // namespace margelo::nitro::shield
