// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#include "HybridMetadataTestnet.hpp"
#include "HybridNetworkTestnet.hpp"

namespace margelo::nitro::shield {

// Unified fromFFI function - both namespaces have the same MetadataFFI structure
static inline MetadataObject fromFFI(
#ifndef testnet
    const shield_testnet::MetadataFFI& m
#else
    const shield_testnet::MetadataFFI& m
#endif
) {
  return MetadataObject{std::string(m.name), std::string(m.locator), std::string(m.prover), std::string(m.verifier),
                        std::string(m.verifying_key)};
}

// Helper function to get current network as string
static inline std::string getCurrentNetwork() {
  return HybridNetworkTestnet::getNetworkStatic();
}

MetadataObject HybridMetadataTestnet::bond_public() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_bond_public(rust::String(network))
#else
      shield_testnet::metadata_bond_public(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::bond_validator() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_bond_validator(rust::String(network))
#else
      shield_testnet::metadata_bond_validator(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::claim_unbond_public() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_claim_unbond_public(rust::String(network))
#else
      shield_testnet::metadata_claim_unbond_public(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::fee_private() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_fee_private(rust::String(network))
#else
      shield_testnet::metadata_fee_private(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::fee_public() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_fee_public(rust::String(network))
#else
      shield_testnet::metadata_fee_public(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::inclusion() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_inclusion(rust::String(network))
#else
      shield_testnet::metadata_inclusion(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::join() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_join(rust::String(network))
#else
      shield_testnet::metadata_join(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::set_validator_state() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_set_validator_state(rust::String(network))
#else
      shield_testnet::metadata_set_validator_state(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::split() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_split(rust::String(network))
#else
      shield_testnet::metadata_split(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::transfer_private() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_transfer_private(rust::String(network))
#else
      shield_testnet::metadata_transfer_private(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::transfer_private_to_public() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_transfer_private_to_public(rust::String(network))
#else
      shield_testnet::metadata_transfer_private_to_public(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::transfer_public() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_transfer_public(rust::String(network))
#else
      shield_testnet::metadata_transfer_public(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::transfer_public_as_signer() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_transfer_public_as_signer(rust::String(network))
#else
      shield_testnet::metadata_transfer_public_as_signer(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::transfer_public_to_private() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_transfer_public_to_private(rust::String(network))
#else
      shield_testnet::metadata_transfer_public_to_private(rust::String(network))
#endif
      ;
  return fromFFI(m);
}
MetadataObject HybridMetadataTestnet::unbond_public() {
  std::string network = getCurrentNetwork();
  auto m =
#ifndef testnet
      shield_testnet::metadata_unbond_public(rust::String(network))
#else
      shield_testnet::metadata_unbond_public(rust::String(network))
#endif
      ;
  return fromFFI(m);
}

} // namespace margelo::nitro::shield
