// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

// AUTO-GENERATED STYLE WRAPPER (hand-written implementation)
#pragma once

#include "HybridOfflineQuerySpec.hpp"
#include <NitroModules/ArrayBuffer.hpp>
#include <memory>
#include <string>
#ifndef testnet
#include "rust/shield_testnet.h"
#else
#include "rust/shield_testnet.h"
#endif

namespace margelo::nitro::shield {

class HybridOfflineQueryTestnet : public HybridOfflineQuerySpec {
 public:
  explicit HybridOfflineQueryTestnet() : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()) {}
  ~HybridOfflineQueryTestnet() override;

  std::shared_ptr<ArrayBuffer> toBytes() override;
  void initWithBytes(const std::shared_ptr<ArrayBuffer>& bytes) override;
  void initWithString(const std::string& json) override;
  void addBlockHeight(double height) override;
  void addStatePath(const std::string& commitment, const std::string& statePath) override;

  uint64_t getHandle() const {
    return _handle;
  }

 private:
  uint64_t _handle{0};
};

} // namespace margelo::nitro::shield
