// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#include "HybridProgramManagerTestnet.hpp"
#include "HybridAuthorizationTestnet.hpp"
#include "HybridOfflineQueryTestnet.hpp"
#include "HybridPrivateKeyTestnet.hpp"
#include "HybridProgramTestnet.hpp"
#include "HybridProvingKeyTestnet.hpp"
#include "HybridProvingRequestTestnet.hpp"
#include "HybridTransactionTestnet.hpp"
#include "HybridVerifyingKeyTestnet.hpp"
#include "HybridViewKeyTestnet.hpp"
#ifndef testnet
#include "rust/shield_testnet.h"
#else
#include "rust/shield_testnet.h"
#endif
#include <algorithm>
#include <chrono>
#include <limits>
#include <memory>
#include <stdexcept>
#include <string>
#include <thread>
#include <unordered_map>
#include <variant>
#include <vector>

using namespace margelo::nitro;
using namespace margelo::nitro::shield;

namespace {
uint64_t toUnsignedOrThrow(int64_t value, const char* fieldName) {
  if (value < 0) {
    throw std::invalid_argument(std::string(fieldName) + " cannot be negative");
  }
  return static_cast<uint64_t>(value);
}
} // namespace

namespace margelo::nitro::shield {

// Build an authorization for program execution
std::shared_ptr<HybridAuthorizationSpec>
HybridProgramManagerTestnet::buildAuthorization(const std::string& programName, const std::string& functionName,
                                         const std::vector<std::string>& inputs, const std::shared_ptr<HybridPrivateKeySpec>& privateKey,
                                         const std::string& programSource,
                                         const std::unordered_map<std::string, std::string>& programImports, double edition) {
  try {
    validateInputs(programName, functionName, inputs);
    validatePrivateKey(privateKey);

    // Cast to concrete type to access the handle
    auto concretePrivateKey = std::dynamic_pointer_cast<HybridPrivateKeyTestnet>(privateKey);
    if (!concretePrivateKey) {
      throw std::runtime_error("Invalid private key type");
    }

    auto privateKeyHandle = concretePrivateKey->getHandle();
    shield_testnet::PrivateKeyHandle handle = {privateKeyHandle};

    // Convert imports to the format expected by Rust (key=value strings)
    rust::Vec<rust::String> importsList;
    for (const auto& import : programImports) {
      std::string importStr = import.first + "=" + import.second;
      importsList.push_back(rust::String(importStr));
    }

    // Convert inputs to rust vector
    rust::Vec<rust::String> rustInputs;
    for (const auto& input : inputs) {
      rustInputs.push_back(rust::String(input));
    }

    // Call Rust FFI function
    auto result = shield_testnet::program_manager_build_authorization(rust::String(programName), rust::String(functionName), rustInputs,
                                                                       handle, rust::String(programSource), importsList, edition);

    if (!result.success) {
      throw std::runtime_error("Rust authorization failed: " + std::string(result.error));
    }

    // Create and return the authorization wrapper
    return std::make_shared<HybridAuthorizationTestnet>(result.handle);

  } catch (const std::exception& e) {
    throw std::runtime_error("Failed to build authorization: " + std::string(e.what()));
  }
}

// Build a fee authorization for transactions
std::shared_ptr<HybridAuthorizationSpec>
HybridProgramManagerTestnet::buildFeeAuthorization(const std::string& deploymentOrExecutionId, int64_t baseFeeCredits, int64_t priorityFeeCredits,
                                            const std::shared_ptr<HybridPrivateKeySpec>& privateKey, const std::string& feeRecord) {
  try {
    validatePrivateKey(privateKey);

    if (deploymentOrExecutionId.empty()) {
      throw std::invalid_argument("Deployment or execution ID cannot be empty");
    }

    // Cast to concrete type to access the handle
    auto concretePrivateKey = std::dynamic_pointer_cast<HybridPrivateKeyTestnet>(privateKey);
    if (!concretePrivateKey) {
      throw std::runtime_error("Invalid private key type");
    }

    auto privateKeyHandle = concretePrivateKey->getHandle();
    shield_testnet::PrivateKeyHandle handle = {privateKeyHandle};

    // Call Rust FFI function
    auto result = shield_testnet::program_manager_build_fee_authorization(
        rust::String(deploymentOrExecutionId), toUnsignedOrThrow(baseFeeCredits, "baseFeeCredits"),
        toUnsignedOrThrow(priorityFeeCredits, "priorityFeeCredits"), handle, rust::String(feeRecord));

    if (!result.success) {
      throw std::runtime_error("Rust fee authorization failed: " + std::string(result.error));
    }

    // Create and return the fee authorization wrapper
    return std::make_shared<HybridAuthorizationTestnet>(result.handle);

  } catch (const std::exception& e) {
    throw std::runtime_error("Failed to build fee authorization: " + std::string(e.what()));
  }
}

// Estimate minimum execution fee (microcredits)
int64_t HybridProgramManagerTestnet::estimateExecutionFee(const std::string& program, const std::optional<std::string>& functionName,
                                                  const std::optional<std::unordered_map<std::string, std::string>>& imports,
                                                  std::optional<double> edition) {
  try {
    // Convert imports to key=value list
    rust::Vec<rust::String> importsList;
    if (imports.has_value()) {
      for (const auto& kv : imports.value()) {
        std::string importStr = kv.first + "=" + kv.second;
        importsList.push_back(rust::String(importStr));
      }
    }
    double usedEdition = edition.has_value() ? edition.value() : 0.0;
#ifndef testnet
    auto result = shield_testnet::program_manager_estimate_execution_fee(
#else
    auto result = shield_testnet::program_manager_estimate_execution_fee(
#endif
        rust::String(program), rust::String(functionName.value_or(std::string{})), importsList, usedEdition);
    if (!result.success) {
      throw std::runtime_error("Rust estimateExecutionFee failed: " + std::string(result.error));
    }
    // Parse decimal string to double
    unsigned long long micro = 0;
    try {
      micro = std::stoull(std::string(result.result));
    } catch (...) {
      throw std::runtime_error("Failed to parse estimateExecutionFee result");
    }
    return static_cast<int64_t>(micro);
  } catch (const std::exception& e) {
    throw std::runtime_error("Failed to estimate execution fee: " + std::string(e.what()));
  }
}

int64_t HybridProgramManagerTestnet::estimateDeploymentFee(const std::string& programString,
                                                   const std::unordered_map<std::string, std::string>& imports) {
  try {
    // Convert imports to key=value list
    rust::Vec<rust::String> importsList;
    for (const auto& kv : imports) {
      std::string importStr = kv.first + "=" + kv.second;
      importsList.push_back(rust::String(importStr));
    }
#ifndef testnet
    auto result = shield_testnet::program_manager_estimate_deployment_fee(
#else
    auto result = shield_testnet::program_manager_estimate_deployment_fee(
#endif
        rust::String(programString), importsList);
    if (!result.success) {
      throw std::runtime_error("Rust estimateDeploymentFee failed: " + std::string(result.error));
    }
    // Parse decimal string to double
    unsigned long long micro = 0;
    try {
      micro = std::stoull(std::string(result.result));
    } catch (...) {
      throw std::runtime_error("Failed to parse estimateDeploymentFee result");
    }
    return static_cast<int64_t>(micro);
  } catch (const std::exception& e) {
    throw std::runtime_error("Failed to estimate deployment fee: " + std::string(e.what()));
  }
}

int64_t HybridProgramManagerTestnet::estimateFeeForAuthorization(const std::string& programSource,
                                                         const std::optional<std::shared_ptr<HybridAuthorizationSpec>>& authorization,
                                                         const std::optional<std::unordered_map<std::string, std::string>>& imports,
                                                         std::optional<double> edition) {
  try {
    // Convert imports to key=value list
    rust::Vec<rust::String> importsList;
    if (imports.has_value()) {
      for (const auto& kv : imports.value()) {
        std::string importStr = kv.first + "=" + kv.second;
        importsList.push_back(rust::String(importStr));
      }
    }
    // Obtain a temporary authorization handle by round-tripping via string
    auto concreteAuth = std::dynamic_pointer_cast<HybridAuthorizationTestnet>(authorization.value());
    if (!concreteAuth) {
      throw std::runtime_error("Invalid authorization type");
    }
#ifndef testnet
    auto authRes = shield_testnet::authorization_from_string(rust::String(concreteAuth->toString()));
#else
    auto authRes = shield_testnet::authorization_from_string(rust::String(concreteAuth->toString()));
#endif
    if (!authRes.success) {
      throw std::runtime_error("Failed to materialize authorization handle: " + std::string(authRes.error));
    }
    uint64_t authHandle = authRes.handle;
    double usedEdition = edition.has_value() ? edition.value() : 0.0;
#ifndef testnet
    auto result = shield_testnet::program_manager_estimate_fee_for_authorization(
#else
    auto result = shield_testnet::program_manager_estimate_fee_for_authorization(
#endif
        rust::String(programSource), authHandle, importsList, usedEdition);
    if (!result.success) {
#ifndef testnet
      shield_testnet::destroy_authorization(authRes.handle);
#else
      shield_testnet::destroy_authorization(authRes.handle);
#endif
      throw std::runtime_error("Rust estimateFeeForAuthorization failed: " + std::string(result.error));
    }
    // Parse decimal string to double
    unsigned long long micro = 0;
    try {
      micro = std::stoull(std::string(result.result));
    } catch (...) {
      throw std::runtime_error("Failed to parse estimateFeeForAuthorization result");
    }
    int64_t out = static_cast<int64_t>(micro);
#ifndef testnet
    shield_testnet::destroy_authorization(authRes.handle);
#else
    shield_testnet::destroy_authorization(authRes.handle);
#endif
    return out;
  } catch (const std::exception& e) {
    throw std::runtime_error("Failed to estimate fee for authorization: " + std::string(e.what()));
  }
}

// Build a complete execution transaction
std::shared_ptr<Promise<std::shared_ptr<HybridTransactionSpec>>> HybridProgramManagerTestnet::buildExecutionTransaction(
    const std::shared_ptr<HybridPrivateKeySpec>& privateKey, const std::string& program, const std::string& functionName,
    const std::vector<std::string>& inputs, int64_t priorityFee, const std::optional<RecordPlaintext>& feeRecord,
    const std::optional<std::string>& url,
    const std::optional<std::unordered_map<std::string, std::variant<std::shared_ptr<HybridProgramSpec>, std::string>>>& imports,
    const std::optional<std::shared_ptr<HybridProvingKeySpec>>& /*provingKey*/,
    const std::optional<std::shared_ptr<HybridVerifyingKeySpec>>& /*verifyingKey*/,
    const std::optional<std::shared_ptr<HybridProvingKeySpec>>& feeProvingKey,
    const std::optional<std::shared_ptr<HybridVerifyingKeySpec>>& feeVerifyingKey,
    const std::optional<std::shared_ptr<HybridOfflineQuerySpec>>& offlineQuery, std::optional<double> edition) {
  try {
    // We still validate inputs using the program identifier we pass along
    validateInputs(program, functionName, inputs);
    validatePrivateKey(privateKey);

    // Cast to concrete type to access the handle
    auto concretePrivateKey = std::dynamic_pointer_cast<HybridPrivateKeyTestnet>(privateKey);
    if (!concretePrivateKey) {
      throw std::runtime_error("Invalid private key type");
    }

    auto privateKeyHandle = concretePrivateKey->getHandle();
    shield_testnet::PrivateKeyHandle handle = {privateKeyHandle};

    // Convert imports to the format expected by Rust (key=value strings)
    rust::Vec<rust::String> importsList;
    if (imports.has_value()) {
      for (const auto& import : imports.value()) {
        std::string importValue;
        if (std::holds_alternative<std::string>(import.second)) {
          importValue = std::get<std::string>(import.second);
        } else {
          // It's a Program, convert to string
          auto programPtr = std::get<std::shared_ptr<HybridProgramSpec>>(import.second);
          auto concreteProgram = std::dynamic_pointer_cast<HybridProgramTestnet>(programPtr);
          if (!concreteProgram) {
            throw std::runtime_error("Invalid program type in imports");
          }
          importValue = concreteProgram->toString();
        }
        std::string importStr = import.first + "=" + importValue;
        importsList.push_back(rust::String(importStr));
      }
    }

    // Convert inputs to rust vector
    rust::Vec<rust::String> rustInputs;
    for (const auto& input : inputs) {
      rustInputs.push_back(rust::String(input));
    }

    // Determine fee mode and fee record string
    bool privateFee = feeRecord.has_value();
    std::string feeRecordStr;
    if (privateFee) {
      feeRecordStr = feeRecord->name;
    }

    double usedEdition = edition.has_value() ? edition.value() : 0.0;
    auto feePkHandleId = feeProvingKey.has_value() ? std::dynamic_pointer_cast<HybridProvingKeyTestnet>(feeProvingKey.value())->getHandle() : 0ULL;
    auto feeVkHandleId =
        feeVerifyingKey.has_value() ? std::dynamic_pointer_cast<HybridVerifyingKeyTestnet>(feeVerifyingKey.value())->getHandle() : 0ULL;
    auto offlineHandleId =
        offlineQuery.has_value() ? std::dynamic_pointer_cast<HybridOfflineQueryTestnet>(offlineQuery.value())->getHandle() : 0ULL;

    // Call Rust FFI function (new 1:1 signature under canonical name)
#ifndef testnet
    auto result = shield_testnet::program_manager_build_execution_transaction(
#else
    auto result = shield_testnet::program_manager_build_execution_transaction(
#endif
        /* private_key_handle */ handle,
        /* program_source */ rust::String(program),
        /* function_name */ rust::String(functionName),
        /* inputs */ rustInputs,
        /* priority_fee_credits */ toUnsignedOrThrow(priorityFee, "priorityFee"),
        /* fee_record */ rust::String(feeRecordStr),
        /* url */ rust::String(url.has_value() ? url.value() : std::string{}),
        /* imports */ importsList,
        /* fee_proving_key_handle_id */ feePkHandleId,
        /* fee_verifying_key_handle_id */ feeVkHandleId,
        /* offline_query_handle_id */ offlineHandleId,
        /* edition */ usedEdition);

    if (!result.success) {
      return Promise<std::shared_ptr<HybridTransactionSpec>>::rejected(
          std::make_exception_ptr(std::runtime_error("Rust execution transaction failed: " + std::string(result.error))));
    }

    return Promise<std::shared_ptr<HybridTransactionSpec>>::resolved(
        HybridTransactionTestnet::createFromString(std::string(result.result)));

  } catch (const std::exception& e) {
    return Promise<std::shared_ptr<HybridTransactionSpec>>::rejected(
        std::make_exception_ptr(std::runtime_error("Failed to build execution transaction: " + std::string(e.what()))));
  }
}

std::shared_ptr<Promise<std::shared_ptr<HybridProvingRequestSpec>>> HybridProgramManagerTestnet::buildProvingRequest(
    const std::shared_ptr<HybridPrivateKeySpec>& privateKey, const std::string& program, const std::string& functionName,
    const std::vector<std::string>& inputs, int64_t baseFeeCredits, int64_t priorityFeeCredits,
    const std::optional<std::variant<nitro::NullType, RecordPlaintext>>& feeRecord,
    const std::unordered_map<std::string, std::string>& imports, bool broadcast, bool unchecked, double edition,
    bool useFeeMaster) {
  try {
    validateInputs(program, functionName, inputs);
    validatePrivateKey(privateKey);

    auto concretePrivateKey = std::dynamic_pointer_cast<HybridPrivateKeyTestnet>(privateKey);
    if (!concretePrivateKey) {
      throw std::runtime_error("Invalid private key type");
    }

    auto privateKeyHandle = concretePrivateKey->getHandle();
    shield_testnet::PrivateKeyHandle handle = {privateKeyHandle};

    rust::Vec<rust::String> importsList;
    for (const auto& entry : imports) {
      std::string importStr = entry.first + "=" + entry.second;
      importsList.push_back(rust::String(importStr));
    }

    rust::Vec<rust::String> rustInputs;
    for (const auto& input : inputs) {
      rustInputs.push_back(rust::String(input));
    }

    std::string feeRecordStr;
    if (feeRecord.has_value() && std::holds_alternative<RecordPlaintext>(feeRecord.value())) {
      const auto& record = std::get<RecordPlaintext>(feeRecord.value());
      auto promise = record.asString();
      if (!promise) {
        throw std::runtime_error("feeRecord.asString() returned null promise");
      }
      auto maxWait = std::chrono::milliseconds(1000);
      auto start = std::chrono::steady_clock::now();
      while (!promise->isResolved() && !promise->isRejected() && std::chrono::steady_clock::now() - start < maxWait) {
        std::this_thread::sleep_for(std::chrono::milliseconds(1));
      }
      if (promise->isResolved()) {
        feeRecordStr = promise->getResult();
      } else if (promise->isRejected()) {
        throw std::runtime_error("feeRecord.asString() rejected");
      } else {
        throw std::runtime_error("feeRecord.asString() timeout");
      }
    }

#ifndef testnet
    auto result = shield_testnet::program_manager_build_proving_request(
#else
    auto result = shield_testnet::program_manager_build_proving_request(
#endif
        handle, rust::String(program), rust::String(functionName), rustInputs, toUnsignedOrThrow(baseFeeCredits, "baseFeeCredits"),
        toUnsignedOrThrow(priorityFeeCredits, "priorityFeeCredits"),
        rust::String(feeRecordStr), importsList, broadcast, unchecked, edition, useFeeMaster);

    if (!result.success) {
      return Promise<std::shared_ptr<HybridProvingRequestSpec>>::rejected(
          std::make_exception_ptr(std::runtime_error("Rust build proving request failed: " + std::string(result.error))));
    }

    return Promise<std::shared_ptr<HybridProvingRequestSpec>>::resolved(
        std::make_shared<HybridProvingRequestTestnet>(result.handle));
  } catch (const std::exception& e) {
    return Promise<std::shared_ptr<HybridProvingRequestSpec>>::rejected(
        std::make_exception_ptr(std::runtime_error("Failed to build proving request: " + std::string(e.what()))));
  }
}

std::shared_ptr<HybridTransactionSpec> HybridProgramManagerTestnet::buildDeploymentTransaction(
    const std::shared_ptr<HybridPrivateKeySpec>& privateKey, const std::string& program, int64_t priorityFee,
    const std::optional<RecordPlaintext>& feeRecord, const std::string& url,
    const std::unordered_map<std::string, std::variant<std::shared_ptr<HybridProgramSpec>, std::string>>& imports,
    const std::shared_ptr<HybridProvingKeySpec>& feeProvingKey, const std::shared_ptr<HybridVerifyingKeySpec>& verifyingKey,
    const std::optional<std::shared_ptr<HybridOfflineQuerySpec>>& offlineQuery) {
  try {
    const uint64_t priorityFeeCredits = toUnsignedOrThrow(priorityFee, "priorityFee");
    validatePrivateKey(privateKey);

    // Cast to concrete type to access the handle
    auto concretePrivateKey = std::dynamic_pointer_cast<HybridPrivateKeyTestnet>(privateKey);
    if (!concretePrivateKey) {
      throw std::runtime_error("Invalid private key type");
    }

    auto privateKeyHandle = concretePrivateKey->getHandle();
    shield_testnet::PrivateKeyHandle handle = {privateKeyHandle};

    // Convert fee record to string (handle Promise) - feeRecord is now optional
    std::string feeRecordStr;
    if (feeRecord.has_value()) {
      auto promise = feeRecord->asString();
      if (!promise) {
        throw std::runtime_error("feeRecord.asString() returned null promise");
      }
      auto maxWait = std::chrono::milliseconds(1000);
      auto start = std::chrono::steady_clock::now();
      while (!promise->isResolved() && !promise->isRejected() && std::chrono::steady_clock::now() - start < maxWait) {
        std::this_thread::sleep_for(std::chrono::milliseconds(1));
      }
      if (promise->isResolved()) {
        feeRecordStr = promise->getResult();
      } else if (promise->isRejected()) {
        throw std::runtime_error("feeRecord.asString() rejected");
      } else {
        throw std::runtime_error("feeRecord.asString() timeout");
      }
    }

    // Convert imports to the format expected by Rust (key=value strings)
    rust::Vec<rust::String> importsList;
    for (const auto& import : imports) {
      std::string importValue;
      if (std::holds_alternative<std::string>(import.second)) {
        importValue = std::get<std::string>(import.second);
      } else {
        // It's a Program, convert to string
        auto programPtr = std::get<std::shared_ptr<HybridProgramSpec>>(import.second);
        auto concreteProgram = std::dynamic_pointer_cast<HybridProgramTestnet>(programPtr);
        if (!concreteProgram) {
          throw std::runtime_error("Invalid program type in imports");
        }
        importValue = concreteProgram->toString();
      }
      std::string importStr = import.first + "=" + importValue;
      importsList.push_back(rust::String(importStr));
    }

    // Get handle IDs for fee keys
    auto feePkHandleId = feeProvingKey ? std::dynamic_pointer_cast<HybridProvingKeyTestnet>(feeProvingKey)->getHandle() : 0ULL;
    auto feeVkHandleId = verifyingKey ? std::dynamic_pointer_cast<HybridVerifyingKeyTestnet>(verifyingKey)->getHandle() : 0ULL;
    // Get offline query handle if provided
    auto offlineHandleId = offlineQuery.has_value() && offlineQuery.value()
                               ? std::dynamic_pointer_cast<HybridOfflineQueryTestnet>(offlineQuery.value())->getHandle()
                               : 0ULL;

    // Call Rust FFI function
#ifndef testnet
    auto result = shield_testnet::program_manager_build_deployment_transaction(
#else
    auto result = shield_testnet::program_manager_build_deployment_transaction(
#endif
        /* private_key_handle */ handle,
        /* program */ rust::String(program),
        /* priority_fee_credits */ priorityFeeCredits,
        /* fee_record */ rust::String(feeRecordStr),
        /* url */ rust::String(url),
        /* imports */ importsList,
        /* fee_proving_key_handle_id */ feePkHandleId,
        /* fee_verifying_key_handle_id */ feeVkHandleId,
        /* offline_query_handle_id */ offlineHandleId);

    if (!result.success) {
      throw std::runtime_error("Rust deployment transaction failed: " + std::string(result.error));
    }

    return HybridTransactionTestnet::createFromString(std::string(result.result));

  } catch (const std::exception& e) {
    throw std::runtime_error("Failed to build deployment transaction: " + std::string(e.what()));
  }
}

void HybridProgramManagerTestnet::loadInclusionProver(const std::shared_ptr<HybridProvingKeySpec>& provingKey) {
  // Cast to concrete type to access the handle
  auto concreteProvingKey = std::dynamic_pointer_cast<HybridProvingKeyTestnet>(provingKey);
  // Fallback: try static_pointer_cast if dynamic cast fails due to no RTTI or different hierarchy
  if (!concreteProvingKey) {
    concreteProvingKey = std::static_pointer_cast<HybridProvingKeyTestnet>(provingKey);
  }
  if (!concreteProvingKey) {
    throw std::runtime_error("Invalid proving key type");
  }
#ifndef testnet
  shield_testnet::ProvingKeyHandle handle = {concreteProvingKey->getHandle()};
  auto result = shield_testnet::program_manager_load_inclusion_prover(handle);
#else
  shield_testnet::ProvingKeyHandle handle = {concreteProvingKey->getHandle()};
  auto result = shield_testnet::program_manager_load_inclusion_prover(handle);
#endif
  if (!result.success) {
    throw std::runtime_error("Failed to load inclusion prover");
  }
}

// Helper methods

void HybridProgramManagerTestnet::validateInputs(const std::string& programName, const std::string& functionName,
                                          const std::vector<std::string>& inputs) const {
  if (programName.empty()) {
    throw std::invalid_argument("Program name cannot be empty");
  }

  if (functionName.empty()) {
    throw std::invalid_argument("Function name cannot be empty");
  }

  // Validate program name format (should end with .aleo)
  if (programName.find(".aleo") == std::string::npos) {
    throw std::invalid_argument("Program name must end with .aleo");
  }

  // Validate function name format (should be valid identifier)
  if (!std::all_of(functionName.begin(), functionName.end(), [](char c) { return std::isalnum(c) || c == '_'; })) {
    throw std::invalid_argument("Function name contains invalid characters");
  }
}

void HybridProgramManagerTestnet::validatePrivateKey(const std::shared_ptr<HybridPrivateKeySpec>& privateKey) const {
  try {
    if (!privateKey) {
      throw std::invalid_argument("Private key is null");
    }

    // Try to get the string representation to validate the key
    std::string keyString = privateKey->toString();

    if (keyString.empty()) {
      throw std::invalid_argument("Private key toString returned empty string");
    }

    // Basic validation - check if it looks like an Aleo private key
    if (keyString.find("APrivateKey") != 0) {
      throw std::invalid_argument("Invalid private key format");
    }

  } catch (const std::exception& e) {
    throw std::invalid_argument("Invalid private key: " + std::string(e.what()));
  }
}

std::string HybridProgramManagerTestnet::recordPlaintextToCommitment(const std::string& recordPlaintext, const std::string& programId,
                                                              const std::string& recordName,
                                                              const std::shared_ptr<HybridViewKeySpec>& viewKey) {
  try {
    // Cast to concrete type to access the handle
    auto concreteViewKey = std::dynamic_pointer_cast<HybridViewKeyTestnet>(viewKey);
    if (!concreteViewKey) {
      throw std::runtime_error("Invalid view key type");
    }

    auto viewKeyHandle = concreteViewKey->_viewKeyHandle;
    shield_testnet::ViewKeyHandle handle = {viewKeyHandle};

    // Call Rust FFI function
    auto result = shield_testnet::record_plaintext_to_commitment(rust::String(recordPlaintext), rust::String(programId),
                                                                  rust::String(recordName), handle);

    if (!result.success) {
      throw std::runtime_error("Rust record plaintext to commitment failed: " + std::string(result.error));
    }

    return std::string(result.result);

  } catch (const std::exception& e) {
    throw std::runtime_error("Failed to compute record commitment: " + std::string(e.what()));
  }
}

std::string HybridProgramManagerTestnet::recordPlaintextToSerialNumber(const std::string& recordPlaintext,
                                                                 const std::shared_ptr<HybridPrivateKeySpec>& privateKey,
                                                                 const std::string& programId, const std::string& recordName,
                                                                 const std::string& recordViewKey) {
  try {
    validatePrivateKey(privateKey);

    // Cast to concrete type to access the handle
    auto concretePrivateKey = std::dynamic_pointer_cast<HybridPrivateKeyTestnet>(privateKey);
    if (!concretePrivateKey) {
      throw std::runtime_error("Invalid private key type");
    }

    auto privateKeyHandle = concretePrivateKey->getHandle();
    shield_testnet::PrivateKeyHandle handle = {privateKeyHandle};

    auto result = shield_testnet::record_plaintext_to_serial_number(rust::String(recordPlaintext), handle,
                                                                     rust::String(programId), rust::String(recordName),
                                                                     rust::String(recordViewKey));

    if (!result.success) {
      throw std::runtime_error("Rust record plaintext to serial number failed: " + std::string(result.error));
    }

    return std::string(result.result);

  } catch (const std::exception& e) {
    throw std::runtime_error("Failed to compute serial number: " + std::string(e.what()));
  }
}

} // namespace margelo::nitro::shield
