// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#include "HybridProvingRequestTestnet.hpp"
#include "HybridAuthorizationTestnet.hpp"
#include <NitroModules/ArrayBuffer.hpp>
#include <NitroModules/Promise.hpp>
#include <cstring>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

// Include generated struct headers
#include "AuthorizationJSON.hpp"
#include "ProvingRequestJSON.hpp"

// Include generated Rust cxx bridge header
#ifndef testnet
  #include "rust/shield_testnet.h"
#else
  #include "rust/shield_testnet.h"
#endif

using namespace margelo::nitro;
using namespace margelo::nitro::shield;

namespace margelo::nitro::shield {

// Internal constructor for creating from proving request handle
HybridProvingRequestTestnet::HybridProvingRequestTestnet(uint64_t provingRequestHandle)
    : HybridObject([]() -> const char* { static std::string k = std::string(TAG) + "Testnet"; return k.c_str(); }()), _provingRequestHandle(provingRequestHandle) {}

// Destructor - clean up Rust resources
HybridProvingRequestTestnet::~HybridProvingRequestTestnet() {
  if (_provingRequestHandle != 0) {
    shield_testnet::destroy_proving_request(_provingRequestHandle);
  }
}

// Factory methods
std::shared_ptr<HybridProvingRequestSpec> HybridProvingRequestTestnet::create(
  const std::shared_ptr<HybridAuthorizationSpec>& authorization,
  const std::optional<std::shared_ptr<HybridAuthorizationSpec>>& feeAuthorization,
  bool broadcast
) {
  return fromAuthorizations(authorization, feeAuthorization, broadcast);
}

std::shared_ptr<HybridProvingRequestSpec> HybridProvingRequestTestnet::createWithFee(const std::shared_ptr<HybridAuthorizationSpec>& authorization, const std::optional<std::shared_ptr<HybridAuthorizationSpec>>& feeAuthorization, bool broadcast) {
  return fromAuthorizations(authorization, feeAuthorization, broadcast);
}

std::shared_ptr<HybridProvingRequestSpec> HybridProvingRequestTestnet::fromString(const std::string& request) {
  auto result = shield_testnet::proving_request_from_string(rust::String(request));
  if (result.success) {
    return std::make_shared<HybridProvingRequestTestnet>(result.handle);
  } else {
    throw std::runtime_error(std::string(result.error));
  }
}

std::shared_ptr<HybridProvingRequestSpec> HybridProvingRequestTestnet::fromBytesLe(const std::shared_ptr<ArrayBuffer>& bytes) {
  rust::Vec<uint8_t> bytesVec;
  for (size_t i = 0; i < bytes->size(); ++i) {
    bytesVec.push_back(bytes->data()[i]);
  }

  auto result = shield_testnet::proving_request_from_bytes_le(bytesVec);
  if (result.success) {
    return std::make_shared<HybridProvingRequestTestnet>(result.handle);
  } else {
    throw std::runtime_error(std::string(result.error));
  }
}

std::shared_ptr<HybridProvingRequestSpec>
HybridProvingRequestTestnet::fromAuthorizations(const std::shared_ptr<HybridAuthorizationSpec>& authorization,
                                         const std::optional<std::shared_ptr<HybridAuthorizationSpec>>& feeAuthorization, bool broadcast) {

  // Extract authorization handle
  auto authImpl = std::static_pointer_cast<HybridAuthorizationTestnet>(authorization);
  uint64_t authHandle = authImpl->_authorizationHandle;

  // Extract fee authorization handle if present
  uint64_t feeAuthHandle = 0;
  if (feeAuthorization.has_value()) {
    auto feeAuthImpl = std::static_pointer_cast<HybridAuthorizationTestnet>(feeAuthorization.value());
    feeAuthHandle = feeAuthImpl->_authorizationHandle;
  }

  auto result = shield_testnet::proving_request_from_authorizations(authHandle, feeAuthHandle, broadcast);
  if (result.success) {
    return std::make_shared<HybridProvingRequestTestnet>(result.handle);
  } else {
    throw std::runtime_error(std::string(result.error));
  }
}

// Serialization methods
std::string HybridProvingRequestTestnet::toString() {
  if (_provingRequestHandle == 0) {
    throw std::runtime_error("ProvingRequest handle is null");
  }

    auto result = shield_testnet::proving_request_to_json(_provingRequestHandle);
  if (result.success) {
    return std::string(result.result);
  } else {
    throw std::runtime_error(std::string(result.error));
  }
}

std::shared_ptr<ArrayBuffer> HybridProvingRequestTestnet::toBytesLe() {
  if (_provingRequestHandle == 0) {
    throw std::runtime_error("ProvingRequest handle is null");
  }

    auto result = shield_testnet::proving_request_to_bytes_le(_provingRequestHandle);
  if (result.success) {
    auto buffer = ArrayBuffer::allocate(result.bytes.size());
    std::memcpy(buffer->data(), result.bytes.data(), result.bytes.size());
    return buffer;
  } else {
    throw std::runtime_error(std::string(result.error));
  }
}

ProvingRequestJSON HybridProvingRequestTestnet::toJSON() {
  if (_provingRequestHandle == 0) {
    throw std::runtime_error("ProvingRequest handle is null");
  }

  // Get the authorization and convert to JSON
  auto auth = authorization();
  auto authImpl = std::static_pointer_cast<HybridAuthorizationTestnet>(auth);
  AuthorizationJSON authJSON = authImpl->toJSON();

  // Get the fee authorization (optional) and convert to JSON
  std::optional<AuthorizationJSON> feeAuthJSON;
  auto feeAuth = feeAuthorization();
  if (feeAuth.has_value()) {
    auto feeAuthImpl = std::static_pointer_cast<HybridAuthorizationTestnet>(feeAuth.value());
    feeAuthJSON = feeAuthImpl->toJSON();
  }

  return ProvingRequestJSON(authJSON, feeAuthJSON, broadcast());
}

// Accessors
std::shared_ptr<HybridAuthorizationSpec> HybridProvingRequestTestnet::authorization() {
  if (_provingRequestHandle == 0) {
    throw std::runtime_error("ProvingRequest handle is null");
  }

  auto result = shield_testnet::proving_request_get_authorization(_provingRequestHandle);
  if (result.success) {
    return std::make_shared<HybridAuthorizationTestnet>(result.handle);
  } else {
    throw std::runtime_error(std::string(result.error));
  }
}

std::optional<std::shared_ptr<HybridAuthorizationSpec>> HybridProvingRequestTestnet::feeAuthorization() {
  if (_provingRequestHandle == 0) {
    throw std::runtime_error("ProvingRequest handle is null");
  }

  auto result = shield_testnet::proving_request_get_fee_authorization(_provingRequestHandle);
  if (result.success) {
    return std::make_shared<HybridAuthorizationTestnet>(result.handle);
  } else {
    return std::nullopt;
  }
}

bool HybridProvingRequestTestnet::broadcast() {
  if (_provingRequestHandle == 0) {
    throw std::runtime_error("ProvingRequest handle is null");
  }

  return shield_testnet::proving_request_get_broadcast(_provingRequestHandle);
}

// Utility methods
std::shared_ptr<HybridProvingRequestSpec> HybridProvingRequestTestnet::replicate() {
  if (_provingRequestHandle == 0) {
    throw std::runtime_error("ProvingRequest handle is null");
  }

    auto result = shield_testnet::proving_request_replicate(_provingRequestHandle);
  if (result.success) {
    return std::make_shared<HybridProvingRequestTestnet>(result.handle);
  } else {
    throw std::runtime_error(std::string(result.error));
  }
}

bool HybridProvingRequestTestnet::verify() {
  if (_provingRequestHandle == 0) {
    return false;
  }

  return shield_testnet::proving_request_verify(_provingRequestHandle);
}

bool HybridProvingRequestTestnet::isEqual(const std::shared_ptr<HybridProvingRequestSpec>& other) {
  if (_provingRequestHandle == 0) {
    return false;
  }

  auto otherProvingRequest = std::static_pointer_cast<HybridProvingRequestTestnet>(other);
  if (otherProvingRequest->_provingRequestHandle == 0) {
    return false;
  }

  return shield_testnet::proving_request_equals(_provingRequestHandle, otherProvingRequest->_provingRequestHandle);
}

} // namespace margelo::nitro::shield
