// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by scripts/generate-testnet-variants.cjs
#define testnet 1

#pragma once

#include "HybridGroupSpec.hpp"
#include <optional>
#ifndef testnet
  #include "rust/shield_testnet.h"
#else
  #include "rust/shield_testnet.h"
#endif

namespace margelo::nitro::shield {
class HybridGroupTestnet final : public HybridGroupSpec {
 public:
  HybridGroupTestnet();
  explicit HybridGroupTestnet(rust::Box<shield_testnet::GroupHandle>&& handle);
  ~HybridGroupTestnet() override;

  std::shared_ptr<HybridGroupSpec> fromString(const std::string& value) override;
  std::shared_ptr<HybridGroupSpec> clone() override;
  std::string toString() override;

  static std::shared_ptr<HybridGroupSpec> create();

 private:
  shield_testnet::GroupHandle& ensureHandle() const;
  static rust::Box<shield_testnet::GroupHandle> createHandle(const std::string& value);
  static rust::Box<shield_testnet::GroupHandle> cloneHandle(shield_testnet::GroupHandle& handle);
  void release();

 private:
  mutable std::optional<rust::Box<shield_testnet::GroupHandle>> handle_;
};

} // namespace margelo::nitro::shield
