name: Use build
description: Uses the build artifacts
runs:
    using: "composite"
    steps:
        - name: Download build
          uses: actions/download-artifact@v4
          with:
              name: build
