[toolchain]
<<<<<<< HEAD
channel = "nightly-2025-08-28"
=======
channel = "nightly-2025-08-15"
>>>>>>> 3a6e8884 (Upgrading rust version)
components = [ "rust-std", "rust-src" ]
targets = [ "wasm32-unknown-unknown" ]
