[build]
rustflags=[
    # Enables multi-threading
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-C", "link-arg=--max-memory=4294967296",

    # Strips out debug information
    "-Z", "location-detail=none",
    "-Z", "fmt-debug=none",
]
