declare module "@provablehq/wasm/testnet.js" {
    export type Address = any;
    export type Authorization = any;
    export type Boolean = any;
    export type BHP256 = any;
    export type BHP512 = any;
    export type BHP768 = any;
    export type BHP1024 = any;
    export type Ciphertext = any;
    export type ComputeKey = any;
    export type EncryptionToolkit = any;
    export type ExecutionRequest = any;
    export type Execution = any;
    export type ExecutionResponse = any;
    export type Field = any;
    export type GraphKey = any;
    export type Group = any;
    export type I8 = any;
    export type I16 = any;
    export type I32 = any;
    export type I64 = any;
    export type I128 = any;
    export type OfflineQuery = any;
    export type Metadata = any;
    export type Pedersen64 = any;
    export type Pedersen128 = any;
    export type Plaintext = any;
    export type Poseidon2 = any;
    export type Poseidon4 = any;
    export type Poseidon8 = any;
    export type PrivateKey = any;
    export type PrivateKeyCiphertext = any;
    export type Program = any;
    export type ProgramManager = any;
    export type ProvingKey = any;
    export type ProvingRequest = any;
    export type RecordCiphertext = any;
    export type RecordPlaintext = any;
    export type Scalar = any;
    export type Signature = any;
    export type Transaction = any;
    export type Transition = any;
    export type U8 = any;
    export type U16 = any;
    export type U32 = any;
    export type U64 = any;
    export type U128 = any;
    export type VerifyingKey = any;
    export type ViewKey = any;
    export const Address: any;
    export const Authorization: any;
    export const Boolean: any;
    export const BHP256: any;
    export const BHP512: any;
    export const BHP768: any;
    export const BHP1024: any;
    export const Ciphertext: any;
    export const ComputeKey: any;
    export const EncryptionToolkit: any;
    export const ExecutionRequest: any;
    export const Execution: any;
    export const ExecutionResponse: any;
    export const Field: any;
    export const GraphKey: any;
    export const Group: any;
    export const I8: any;
    export const I16: any;
    export const I32: any;
    export const I64: any;
    export const I128: any;
    export const OfflineQuery: any;
    export const Metadata: any;
    export const Pedersen64: any;
    export const Pedersen128: any;
    export const Plaintext: any;
    export const Poseidon2: any;
    export const Poseidon4: any;
    export const Poseidon8: any;
    export const PrivateKey: any;
    export const PrivateKeyCiphertext: any;
    export const Program: any;
    export const ProgramManager: any;
    export const ProvingKey: any;
    export const ProvingRequest: any;
    export const RecordCiphertext: any;
    export const RecordPlaintext: any;
    export const Scalar: any;
    export const Signature: any;
    export const Transaction: any;
    export const Transition: any;
    export const U8: any;
    export const U16: any;
    export const U32: any;
    export const U64: any;
    export const U128: any;
    export const VerifyingKey: any;
    export const ViewKey: any;
    export const initThreadPool: any;
    export const getOrInitConsensusVersionTestHeights: any;
    export const verifyFunctionExecution: any;
}

declare module "@provablehq/wasm/mainnet.js" {
    export * from "@provablehq/wasm/testnet.js";
}
