name: Website
on:
  push:
    branches:
      - mainnet

jobs:
  deploy:
    name: SDK Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-yarn
      - uses: ./.github/actions/setup-rust

      - name: Install and Build
        run: |
          yarn build:all
          cd website
          yarn build
        env:
          CI: ""

      - name: Deploy
        id: modified
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: website/dist
          clean-exclude: '["dev"]'

      - name: Check step output
        run: |
          [[ \
          ${{steps.modified.outputs.deployment-status}} = skipped || \
          ${{steps.modified.outputs.deployment-status}} = success \
          ]]
